// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Normalized event types for kernel + user-space events
type EventType int32

const (
	EventType_EXECVE            EventType = 0
	EventType_OPENAT            EventType = 1
	EventType_NETWORK_CONNECT   EventType = 2
	EventType_MKDIR             EventType = 3
	EventType_UNLINK            EventType = 4
	EventType_IOCTL             EventType = 5
	EventType_NETWORK_BIND      EventType = 6
	EventType_NETWORK_SENDTO    EventType = 7
	EventType_NETWORK_RECVFROM  EventType = 8
	EventType_READ              EventType = 9
	EventType_WRITE             EventType = 10
	EventType_OPEN              EventType = 11
	EventType_CHMOD             EventType = 12
	EventType_CHOWN             EventType = 13
	EventType_RENAME            EventType = 14
	EventType_LINK              EventType = 15
	EventType_SYMLINK           EventType = 16
	EventType_MKNOD             EventType = 17
	EventType_CLONE             EventType = 18
	EventType_EXIT              EventType = 19
	EventType_SOCKET            EventType = 20
	EventType_ACCEPT            EventType = 21
	EventType_ACCEPT4           EventType = 22
	EventType_WRAPPER_INTERCEPT EventType = 23
	EventType_NATIVE_HOOK       EventType = 24
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EXECVE",
		1:  "OPENAT",
		2:  "NETWORK_CONNECT",
		3:  "MKDIR",
		4:  "UNLINK",
		5:  "IOCTL",
		6:  "NETWORK_BIND",
		7:  "NETWORK_SENDTO",
		8:  "NETWORK_RECVFROM",
		9:  "READ",
		10: "WRITE",
		11: "OPEN",
		12: "CHMOD",
		13: "CHOWN",
		14: "RENAME",
		15: "LINK",
		16: "SYMLINK",
		17: "MKNOD",
		18: "CLONE",
		19: "EXIT",
		20: "SOCKET",
		21: "ACCEPT",
		22: "ACCEPT4",
		23: "WRAPPER_INTERCEPT",
		24: "NATIVE_HOOK",
	}
	EventType_value = map[string]int32{
		"EXECVE":            0,
		"OPENAT":            1,
		"NETWORK_CONNECT":   2,
		"MKDIR":             3,
		"UNLINK":            4,
		"IOCTL":             5,
		"NETWORK_BIND":      6,
		"NETWORK_SENDTO":    7,
		"NETWORK_RECVFROM":  8,
		"READ":              9,
		"WRITE":             10,
		"OPEN":              11,
		"CHMOD":             12,
		"CHOWN":             13,
		"RENAME":            14,
		"LINK":              15,
		"SYMLINK":           16,
		"MKNOD":             17,
		"CLONE":             18,
		"EXIT":              19,
		"SOCKET":            20,
		"ACCEPT":            21,
		"ACCEPT4":           22,
		"WRAPPER_INTERCEPT": 23,
		"NATIVE_HOOK":       24,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_tracker_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_tracker_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

type CPUInfo_Core_Type int32

const (
	CPUInfo_Core_PERFORMANCE CPUInfo_Core_Type = 0 // P-core
	CPUInfo_Core_EFFICIENCY  CPUInfo_Core_Type = 1 // E-core
	CPUInfo_Core_HYPERTHREAD CPUInfo_Core_Type = 2 // SMT thread
)

// Enum value maps for CPUInfo_Core_Type.
var (
	CPUInfo_Core_Type_name = map[int32]string{
		0: "PERFORMANCE",
		1: "EFFICIENCY",
		2: "HYPERTHREAD",
	}
	CPUInfo_Core_Type_value = map[string]int32{
		"PERFORMANCE": 0,
		"EFFICIENCY":  1,
		"HYPERTHREAD": 2,
	}
)

func (x CPUInfo_Core_Type) Enum() *CPUInfo_Core_Type {
	p := new(CPUInfo_Core_Type)
	*p = x
	return p
}

func (x CPUInfo_Core_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CPUInfo_Core_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_tracker_proto_enumTypes[1].Descriptor()
}

func (CPUInfo_Core_Type) Type() protoreflect.EnumType {
	return &file_tracker_proto_enumTypes[1]
}

func (x CPUInfo_Core_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CPUInfo_Core_Type.Descriptor instead.
func (CPUInfo_Core_Type) EnumDescriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8, 0, 0}
}

type WrapperResponse_Action int32

const (
	WrapperResponse_ALLOW   WrapperResponse_Action = 0
	WrapperResponse_BLOCK   WrapperResponse_Action = 1
	WrapperResponse_REWRITE WrapperResponse_Action = 2
	WrapperResponse_ALERT   WrapperResponse_Action = 3
)

// Enum value maps for WrapperResponse_Action.
var (
	WrapperResponse_Action_name = map[int32]string{
		0: "ALLOW",
		1: "BLOCK",
		2: "REWRITE",
		3: "ALERT",
	}
	WrapperResponse_Action_value = map[string]int32{
		"ALLOW":   0,
		"BLOCK":   1,
		"REWRITE": 2,
		"ALERT":   3,
	}
)

func (x WrapperResponse_Action) Enum() *WrapperResponse_Action {
	p := new(WrapperResponse_Action)
	*p = x
	return p
}

func (x WrapperResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WrapperResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_tracker_proto_enumTypes[2].Descriptor()
}

func (WrapperResponse_Action) Type() protoreflect.EnumType {
	return &file_tracker_proto_enumTypes[2]
}

func (x WrapperResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WrapperResponse_Action.Descriptor instead.
func (WrapperResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{19, 0}
}

// Represents a process registration request
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Represents a process registration response
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Represents a process unregistration request
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Represents a process unregistration response
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Represents an intercepted eBPF event (e.g., file open, exec)
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	NetDirection  string                 `protobuf:"bytes,8,opt,name=net_direction,json=netDirection,proto3" json:"net_direction,omitempty"`
	NetEndpoint   string                 `protobuf:"bytes,9,opt,name=net_endpoint,json=netEndpoint,proto3" json:"net_endpoint,omitempty"`
	NetBytes      uint32                 `protobuf:"varint,10,opt,name=net_bytes,json=netBytes,proto3" json:"net_bytes,omitempty"`
	NetFamily     string                 `protobuf:"bytes,11,opt,name=net_family,json=netFamily,proto3" json:"net_family,omitempty"`
	Retval        int64                  `protobuf:"varint,12,opt,name=retval,proto3" json:"retval,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,13,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	ExtraPath     string                 `protobuf:"bytes,14,opt,name=extra_path,json=extraPath,proto3" json:"extra_path,omitempty"`
	Bytes         uint64                 `protobuf:"varint,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Mode          string                 `protobuf:"bytes,16,opt,name=mode,proto3" json:"mode,omitempty"`
	Domain        string                 `protobuf:"bytes,17,opt,name=domain,proto3" json:"domain,omitempty"`
	SockType      string                 `protobuf:"bytes,18,opt,name=sock_type,json=sockType,proto3" json:"sock_type,omitempty"`
	Protocol      uint32                 `protobuf:"varint,19,opt,name=protocol,proto3" json:"protocol,omitempty"`
	UidArg        uint32                 `protobuf:"varint,20,opt,name=uid_arg,json=uidArg,proto3" json:"uid_arg,omitempty"`
	GidArg        uint32                 `protobuf:"varint,21,opt,name=gid_arg,json=gidArg,proto3" json:"gid_arg,omitempty"`
	EventType     EventType              `protobuf:"varint,22,opt,name=event_type,json=eventType,proto3,enum=pb.EventType" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Event) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Event) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Event) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Event) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Event) GetNetDirection() string {
	if x != nil {
		return x.NetDirection
	}
	return ""
}

func (x *Event) GetNetEndpoint() string {
	if x != nil {
		return x.NetEndpoint
	}
	return ""
}

func (x *Event) GetNetBytes() uint32 {
	if x != nil {
		return x.NetBytes
	}
	return 0
}

func (x *Event) GetNetFamily() string {
	if x != nil {
		return x.NetFamily
	}
	return ""
}

func (x *Event) GetRetval() int64 {
	if x != nil {
		return x.Retval
	}
	return 0
}

func (x *Event) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *Event) GetExtraPath() string {
	if x != nil {
		return x.ExtraPath
	}
	return ""
}

func (x *Event) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Event) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Event) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Event) GetSockType() string {
	if x != nil {
		return x.SockType
	}
	return ""
}

func (x *Event) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Event) GetUidArg() uint32 {
	if x != nil {
		return x.UidArg
	}
	return 0
}

func (x *Event) GetGidArg() uint32 {
	if x != nil {
		return x.GidArg
	}
	return 0
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EXECVE
}

// Batch of events for WebSocket delivery efficiency
type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Represents system process information for the tree view
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float64                `protobuf:"fixed64,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           float32                `protobuf:"fixed32,5,opt,name=mem,proto3" json:"mem,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	GpuMem        uint32                 `protobuf:"varint,7,opt,name=gpu_mem,json=gpuMem,proto3" json:"gpu_mem,omitempty"`    // GPU VRAM usage in MiB
	GpuUtil       uint32                 `protobuf:"varint,8,opt,name=gpu_util,json=gpuUtil,proto3" json:"gpu_util,omitempty"` // GPU utilization percentage
	GpuId         uint32                 `protobuf:"varint,9,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`       // GPU index
	Cmdline       string                 `protobuf:"bytes,10,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MinorFaults   uint64                 `protobuf:"varint,12,opt,name=minor_faults,json=minorFaults,proto3" json:"minor_faults,omitempty"` // Page faults that did not require disk I/O
	MajorFaults   uint64                 `protobuf:"varint,13,opt,name=major_faults,json=majorFaults,proto3" json:"major_faults,omitempty"` // Hard page faults that required disk I/O
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Process) GetMem() float32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetGpuMem() uint32 {
	if x != nil {
		return x.GpuMem
	}
	return 0
}

func (x *Process) GetGpuUtil() uint32 {
	if x != nil {
		return x.GpuUtil
	}
	return 0
}

func (x *Process) GetGpuId() uint32 {
	if x != nil {
		return x.GpuId
	}
	return 0
}

func (x *Process) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *Process) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Process) GetMinorFaults() uint64 {
	if x != nil {
		return x.MinorFaults
	}
	return 0
}

func (x *Process) GetMajorFaults() uint64 {
	if x != nil {
		return x.MajorFaults
	}
	return 0
}

type GPUStatus struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Index    uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UtilGpu  uint32                 `protobuf:"varint,3,opt,name=util_gpu,json=utilGpu,proto3" json:"util_gpu,omitempty"`
	UtilMem  uint32                 `protobuf:"varint,4,opt,name=util_mem,json=utilMem,proto3" json:"util_mem,omitempty"`
	MemTotal uint32                 `protobuf:"varint,5,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed  uint32                 `protobuf:"varint,6,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	Temp     uint32                 `protobuf:"varint,7,opt,name=temp,proto3" json:"temp,omitempty"`
	// NVIDIA detailed engine stats
	EncUtil       uint32 `protobuf:"varint,8,opt,name=enc_util,json=encUtil,proto3" json:"enc_util,omitempty"`
	DecUtil       uint32 `protobuf:"varint,9,opt,name=dec_util,json=decUtil,proto3" json:"dec_util,omitempty"`
	SmClockMhz    uint32 `protobuf:"varint,10,opt,name=sm_clock_mhz,json=smClockMhz,proto3" json:"sm_clock_mhz,omitempty"`
	MemClockMhz   uint32 `protobuf:"varint,11,opt,name=mem_clock_mhz,json=memClockMhz,proto3" json:"mem_clock_mhz,omitempty"`
	GfxClockMhz   uint32 `protobuf:"varint,12,opt,name=gfx_clock_mhz,json=gfxClockMhz,proto3" json:"gfx_clock_mhz,omitempty"`
	PowerW        uint32 `protobuf:"varint,13,opt,name=power_w,json=powerW,proto3" json:"power_w,omitempty"`
	PowerLimitW   uint32 `protobuf:"varint,14,opt,name=power_limit_w,json=powerLimitW,proto3" json:"power_limit_w,omitempty"`
	FanSpeed      uint32 `protobuf:"varint,15,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`
	PcieGen       int32  `protobuf:"varint,16,opt,name=pcie_gen,json=pcieGen,proto3" json:"pcie_gen,omitempty"`
	PcieWidth     int32  `protobuf:"varint,17,opt,name=pcie_width,json=pcieWidth,proto3" json:"pcie_width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUStatus) Reset() {
	*x = GPUStatus{}
	mi := &file_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatus) ProtoMessage() {}

func (x *GPUStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatus.ProtoReflect.Descriptor instead.
func (*GPUStatus) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *GPUStatus) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUStatus) GetUtilGpu() uint32 {
	if x != nil {
		return x.UtilGpu
	}
	return 0
}

func (x *GPUStatus) GetUtilMem() uint32 {
	if x != nil {
		return x.UtilMem
	}
	return 0
}

func (x *GPUStatus) GetMemTotal() uint32 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *GPUStatus) GetMemUsed() uint32 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *GPUStatus) GetTemp() uint32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *GPUStatus) GetEncUtil() uint32 {
	if x != nil {
		return x.EncUtil
	}
	return 0
}

func (x *GPUStatus) GetDecUtil() uint32 {
	if x != nil {
		return x.DecUtil
	}
	return 0
}

func (x *GPUStatus) GetSmClockMhz() uint32 {
	if x != nil {
		return x.SmClockMhz
	}
	return 0
}

func (x *GPUStatus) GetMemClockMhz() uint32 {
	if x != nil {
		return x.MemClockMhz
	}
	return 0
}

func (x *GPUStatus) GetGfxClockMhz() uint32 {
	if x != nil {
		return x.GfxClockMhz
	}
	return 0
}

func (x *GPUStatus) GetPowerW() uint32 {
	if x != nil {
		return x.PowerW
	}
	return 0
}

func (x *GPUStatus) GetPowerLimitW() uint32 {
	if x != nil {
		return x.PowerLimitW
	}
	return 0
}

func (x *GPUStatus) GetFanSpeed() uint32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

func (x *GPUStatus) GetPcieGen() int32 {
	if x != nil {
		return x.PcieGen
	}
	return 0
}

func (x *GPUStatus) GetPcieWidth() int32 {
	if x != nil {
		return x.PcieWidth
	}
	return 0
}

type CPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	Cores         []float64              `protobuf:"fixed64,2,rep,packed,name=cores,proto3" json:"cores,omitempty"` // Keep for backward compatibility
	CoreDetails   []*CPUInfo_Core        `protobuf:"bytes,3,rep,name=core_details,json=coreDetails,proto3" json:"core_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *CPUInfo) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CPUInfo) GetCores() []float64 {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *CPUInfo) GetCoreDetails() []*CPUInfo_Core {
	if x != nil {
		return x.CoreDetails
	}
	return nil
}

type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Percent       float32                `protobuf:"fixed32,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Cached        uint64                 `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	Buffers       uint64                 `protobuf:"varint,5,opt,name=buffers,proto3" json:"buffers,omitempty"`
	Shared        uint64                 `protobuf:"varint,6,opt,name=shared,proto3" json:"shared,omitempty"`
	ZramUsed      uint64                 `protobuf:"varint,7,opt,name=zram_used,json=zramUsed,proto3" json:"zram_used,omitempty"`
	ZramTotal     uint64                 `protobuf:"varint,8,opt,name=zram_total,json=zramTotal,proto3" json:"zram_total,omitempty"`
	SwapTotal     uint64                 `protobuf:"varint,9,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64                 `protobuf:"varint,10,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_tracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryInfo) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryInfo) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryInfo) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *MemoryInfo) GetCached() uint64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *MemoryInfo) GetBuffers() uint64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *MemoryInfo) GetShared() uint64 {
	if x != nil {
		return x.Shared
	}
	return 0
}

func (x *MemoryInfo) GetZramUsed() uint64 {
	if x != nil {
		return x.ZramUsed
	}
	return 0
}

func (x *MemoryInfo) GetZramTotal() uint64 {
	if x != nil {
		return x.ZramTotal
	}
	return 0
}

func (x *MemoryInfo) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryInfo) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

type Hook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Installed     bool                   `protobuf:"varint,4,opt,name=installed,proto3" json:"installed,omitempty"`
	TargetCmd     string                 `protobuf:"bytes,5,opt,name=target_cmd,json=targetCmd,proto3" json:"target_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_tracker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{10}
}

func (x *Hook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hook) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *Hook) GetTargetCmd() string {
	if x != nil {
		return x.TargetCmd
	}
	return ""
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Install       bool                   `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_tracker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{11}
}

func (x *HookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HookRequest) GetInstall() bool {
	if x != nil {
		return x.Install
	}
	return false
}

type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_tracker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{12}
}

func (x *HookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RecvBytes     uint64                 `protobuf:"varint,2,opt,name=recv_bytes,json=recvBytes,proto3" json:"recv_bytes,omitempty"`
	SentBytes     uint64                 `protobuf:"varint,3,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_tracker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetRecvBytes() uint64 {
	if x != nil {
		return x.RecvBytes
	}
	return 0
}

func (x *NetworkInterface) GetSentBytes() uint64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

type DiskDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadBytes     uint64                 `protobuf:"varint,2,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    uint64                 `protobuf:"varint,3,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskDevice) Reset() {
	*x = DiskDevice{}
	mi := &file_tracker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskDevice) ProtoMessage() {}

func (x *DiskDevice) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskDevice.ProtoReflect.Descriptor instead.
func (*DiskDevice) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{14}
}

func (x *DiskDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskDevice) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskDevice) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

type IOInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalReadBytes    uint64                 `protobuf:"varint,1,opt,name=total_read_bytes,json=totalReadBytes,proto3" json:"total_read_bytes,omitempty"`
	TotalWriteBytes   uint64                 `protobuf:"varint,2,opt,name=total_write_bytes,json=totalWriteBytes,proto3" json:"total_write_bytes,omitempty"`
	TotalNetRecvBytes uint64                 `protobuf:"varint,3,opt,name=total_net_recv_bytes,json=totalNetRecvBytes,proto3" json:"total_net_recv_bytes,omitempty"`
	TotalNetSentBytes uint64                 `protobuf:"varint,4,opt,name=total_net_sent_bytes,json=totalNetSentBytes,proto3" json:"total_net_sent_bytes,omitempty"`
	Networks          []*NetworkInterface    `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	Disks             []*DiskDevice          `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IOInfo) Reset() {
	*x = IOInfo{}
	mi := &file_tracker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOInfo) ProtoMessage() {}

func (x *IOInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOInfo.ProtoReflect.Descriptor instead.
func (*IOInfo) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{15}
}

func (x *IOInfo) GetTotalReadBytes() uint64 {
	if x != nil {
		return x.TotalReadBytes
	}
	return 0
}

func (x *IOInfo) GetTotalWriteBytes() uint64 {
	if x != nil {
		return x.TotalWriteBytes
	}
	return 0
}

func (x *IOInfo) GetTotalNetRecvBytes() uint64 {
	if x != nil {
		return x.TotalNetRecvBytes
	}
	return 0
}

func (x *IOInfo) GetTotalNetSentBytes() uint64 {
	if x != nil {
		return x.TotalNetSentBytes
	}
	return 0
}

func (x *IOInfo) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *IOInfo) GetDisks() []*DiskDevice {
	if x != nil {
		return x.Disks
	}
	return nil
}

type FaultInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PageFaults     uint64                 `protobuf:"varint,1,opt,name=page_faults,json=pageFaults,proto3" json:"page_faults,omitempty"`                // pgfault
	MajorFaults    uint64                 `protobuf:"varint,2,opt,name=major_faults,json=majorFaults,proto3" json:"major_faults,omitempty"`             // pgmajfault (hard faults)
	MinorFaults    uint64                 `protobuf:"varint,3,opt,name=minor_faults,json=minorFaults,proto3" json:"minor_faults,omitempty"`             // page_faults - major_faults
	PageFaultRate  float64                `protobuf:"fixed64,4,opt,name=page_fault_rate,json=pageFaultRate,proto3" json:"page_fault_rate,omitempty"`    // faults/sec
	MajorFaultRate float64                `protobuf:"fixed64,5,opt,name=major_fault_rate,json=majorFaultRate,proto3" json:"major_fault_rate,omitempty"` // hard faults/sec
	MinorFaultRate float64                `protobuf:"fixed64,6,opt,name=minor_fault_rate,json=minorFaultRate,proto3" json:"minor_fault_rate,omitempty"` // soft faults/sec
	SwapIn         uint64                 `protobuf:"varint,7,opt,name=swap_in,json=swapIn,proto3" json:"swap_in,omitempty"`
	SwapOut        uint64                 `protobuf:"varint,8,opt,name=swap_out,json=swapOut,proto3" json:"swap_out,omitempty"`
	SwapInRate     float64                `protobuf:"fixed64,9,opt,name=swap_in_rate,json=swapInRate,proto3" json:"swap_in_rate,omitempty"`
	SwapOutRate    float64                `protobuf:"fixed64,10,opt,name=swap_out_rate,json=swapOutRate,proto3" json:"swap_out_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FaultInfo) Reset() {
	*x = FaultInfo{}
	mi := &file_tracker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultInfo) ProtoMessage() {}

func (x *FaultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultInfo.ProtoReflect.Descriptor instead.
func (*FaultInfo) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{16}
}

func (x *FaultInfo) GetPageFaults() uint64 {
	if x != nil {
		return x.PageFaults
	}
	return 0
}

func (x *FaultInfo) GetMajorFaults() uint64 {
	if x != nil {
		return x.MajorFaults
	}
	return 0
}

func (x *FaultInfo) GetMinorFaults() uint64 {
	if x != nil {
		return x.MinorFaults
	}
	return 0
}

func (x *FaultInfo) GetPageFaultRate() float64 {
	if x != nil {
		return x.PageFaultRate
	}
	return 0
}

func (x *FaultInfo) GetMajorFaultRate() float64 {
	if x != nil {
		return x.MajorFaultRate
	}
	return 0
}

func (x *FaultInfo) GetMinorFaultRate() float64 {
	if x != nil {
		return x.MinorFaultRate
	}
	return 0
}

func (x *FaultInfo) GetSwapIn() uint64 {
	if x != nil {
		return x.SwapIn
	}
	return 0
}

func (x *FaultInfo) GetSwapOut() uint64 {
	if x != nil {
		return x.SwapOut
	}
	return 0
}

func (x *FaultInfo) GetSwapInRate() float64 {
	if x != nil {
		return x.SwapInRate
	}
	return 0
}

func (x *FaultInfo) GetSwapOutRate() float64 {
	if x != nil {
		return x.SwapOutRate
	}
	return 0
}

type SystemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	Gpus          []*GPUStatus           `protobuf:"bytes,2,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Cpu           *CPUInfo               `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryInfo            `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Io            *IOInfo                `protobuf:"bytes,5,opt,name=io,proto3" json:"io,omitempty"`
	Faults        *FaultInfo             `protobuf:"bytes,6,opt,name=faults,proto3" json:"faults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_tracker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{17}
}

func (x *SystemStats) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *SystemStats) GetGpus() []*GPUStatus {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *SystemStats) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemStats) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemStats) GetIo() *IOInfo {
	if x != nil {
		return x.Io
	}
	return nil
}

func (x *SystemStats) GetFaults() *FaultInfo {
	if x != nil {
		return x.Faults
	}
	return nil
}

type WrapperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperRequest) Reset() {
	*x = WrapperRequest{}
	mi := &file_tracker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperRequest) ProtoMessage() {}

func (x *WrapperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperRequest.ProtoReflect.Descriptor instead.
func (*WrapperRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{18}
}

func (x *WrapperRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WrapperRequest) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *WrapperRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WrapperRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type WrapperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WrapperResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=pb.WrapperResponse_Action" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RewrittenArgs []string               `protobuf:"bytes,3,rep,name=rewritten_args,json=rewrittenArgs,proto3" json:"rewritten_args,omitempty"` // Only if action is REWRITE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperResponse) Reset() {
	*x = WrapperResponse{}
	mi := &file_tracker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperResponse) ProtoMessage() {}

func (x *WrapperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperResponse.ProtoReflect.Descriptor instead.
func (*WrapperResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{19}
}

func (x *WrapperResponse) GetAction() WrapperResponse_Action {
	if x != nil {
		return x.Action
	}
	return WrapperResponse_ALLOW
}

func (x *WrapperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WrapperResponse) GetRewrittenArgs() []string {
	if x != nil {
		return x.RewrittenArgs
	}
	return nil
}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_tracker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{20}
}

func (x *ProcessList) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

type CPUInfo_Core struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Usage         float64                `protobuf:"fixed64,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Type          CPUInfo_Core_Type      `protobuf:"varint,3,opt,name=type,proto3,enum=pb.CPUInfo_Core_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo_Core) Reset() {
	*x = CPUInfo_Core{}
	mi := &file_tracker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo_Core) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo_Core) ProtoMessage() {}

func (x *CPUInfo_Core) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo_Core.ProtoReflect.Descriptor instead.
func (*CPUInfo_Core) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CPUInfo_Core) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CPUInfo_Core) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *CPUInfo_Core) GetType() CPUInfo_Core_Type {
	if x != nil {
		return x.Type
	}
	return CPUInfo_Core_PERFORMANCE
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\x02pb\"#\n" +
	"\x0fRegisterRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x11UnregisterRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc2\x04\n" +
	"\x05Event\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12#\n" +
	"\rnet_direction\x18\b \x01(\tR\fnetDirection\x12!\n" +
	"\fnet_endpoint\x18\t \x01(\tR\vnetEndpoint\x12\x1b\n" +
	"\tnet_bytes\x18\n" +
	" \x01(\rR\bnetBytes\x12\x1d\n" +
	"\n" +
	"net_family\x18\v \x01(\tR\tnetFamily\x12\x16\n" +
	"\x06retval\x18\f \x01(\x03R\x06retval\x12\x1d\n" +
	"\n" +
	"extra_info\x18\r \x01(\tR\textraInfo\x12\x1d\n" +
	"\n" +
	"extra_path\x18\x0e \x01(\tR\textraPath\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\x04R\x05bytes\x12\x12\n" +
	"\x04mode\x18\x10 \x01(\tR\x04mode\x12\x16\n" +
	"\x06domain\x18\x11 \x01(\tR\x06domain\x12\x1b\n" +
	"\tsock_type\x18\x12 \x01(\tR\bsockType\x12\x1a\n" +
	"\bprotocol\x18\x13 \x01(\rR\bprotocol\x12\x17\n" +
	"\auid_arg\x18\x14 \x01(\rR\x06uidArg\x12\x17\n" +
	"\agid_arg\x18\x15 \x01(\rR\x06gidArg\x12,\n" +
	"\n" +
	"event_type\x18\x16 \x01(\x0e2\r.pb.EventTypeR\teventType\"/\n" +
	"\n" +
	"EventBatch\x12!\n" +
	"\x06events\x18\x01 \x03(\v2\t.pb.EventR\x06events\"\xc7\x02\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x05 \x01(\x02R\x03mem\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x17\n" +
	"\agpu_mem\x18\a \x01(\rR\x06gpuMem\x12\x19\n" +
	"\bgpu_util\x18\b \x01(\rR\agpuUtil\x12\x15\n" +
	"\x06gpu_id\x18\t \x01(\rR\x05gpuId\x12\x18\n" +
	"\acmdline\x18\n" +
	" \x01(\tR\acmdline\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x03R\n" +
	"createTime\x12!\n" +
	"\fminor_faults\x18\f \x01(\x04R\vminorFaults\x12!\n" +
	"\fmajor_faults\x18\r \x01(\x04R\vmajorFaults\"\xeb\x03\n" +
	"\tGPUStatus\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\butil_gpu\x18\x03 \x01(\rR\autilGpu\x12\x19\n" +
	"\butil_mem\x18\x04 \x01(\rR\autilMem\x12\x1b\n" +
	"\tmem_total\x18\x05 \x01(\rR\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x06 \x01(\rR\amemUsed\x12\x12\n" +
	"\x04temp\x18\a \x01(\rR\x04temp\x12\x19\n" +
	"\benc_util\x18\b \x01(\rR\aencUtil\x12\x19\n" +
	"\bdec_util\x18\t \x01(\rR\adecUtil\x12 \n" +
	"\fsm_clock_mhz\x18\n" +
	" \x01(\rR\n" +
	"smClockMhz\x12\"\n" +
	"\rmem_clock_mhz\x18\v \x01(\rR\vmemClockMhz\x12\"\n" +
	"\rgfx_clock_mhz\x18\f \x01(\rR\vgfxClockMhz\x12\x17\n" +
	"\apower_w\x18\r \x01(\rR\x06powerW\x12\"\n" +
	"\rpower_limit_w\x18\x0e \x01(\rR\vpowerLimitW\x12\x1b\n" +
	"\tfan_speed\x18\x0f \x01(\rR\bfanSpeed\x12\x19\n" +
	"\bpcie_gen\x18\x10 \x01(\x05R\apcieGen\x12\x1d\n" +
	"\n" +
	"pcie_width\x18\x11 \x01(\x05R\tpcieWidth\"\x84\x02\n" +
	"\aCPUInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12\x14\n" +
	"\x05cores\x18\x02 \x03(\x01R\x05cores\x123\n" +
	"\fcore_details\x18\x03 \x03(\v2\x10.pb.CPUInfo.CoreR\vcoreDetails\x1a\x97\x01\n" +
	"\x04Core\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05usage\x18\x02 \x01(\x01R\x05usage\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.pb.CPUInfo.Core.TypeR\x04type\"8\n" +
	"\x04Type\x12\x0f\n" +
	"\vPERFORMANCE\x10\x00\x12\x0e\n" +
	"\n" +
	"EFFICIENCY\x10\x01\x12\x0f\n" +
	"\vHYPERTHREAD\x10\x02\"\x92\x02\n" +
	"\n" +
	"MemoryInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x02R\apercent\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\x04R\x06cached\x12\x18\n" +
	"\abuffers\x18\x05 \x01(\x04R\abuffers\x12\x16\n" +
	"\x06shared\x18\x06 \x01(\x04R\x06shared\x12\x1b\n" +
	"\tzram_used\x18\a \x01(\x04R\bzramUsed\x12\x1d\n" +
	"\n" +
	"zram_total\x18\b \x01(\x04R\tzramTotal\x12\x1d\n" +
	"\n" +
	"swap_total\x18\t \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\n" +
	" \x01(\x04R\bswapUsed\"\x89\x01\n" +
	"\x04Hook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tinstalled\x18\x04 \x01(\bR\tinstalled\x12\x1d\n" +
	"\n" +
	"target_cmd\x18\x05 \x01(\tR\ttargetCmd\"7\n" +
	"\vHookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\ainstall\x18\x02 \x01(\bR\ainstall\"B\n" +
	"\fHookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"recv_bytes\x18\x02 \x01(\x04R\trecvBytes\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x03 \x01(\x04R\tsentBytes\"`\n" +
	"\n" +
	"DiskDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x02 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x03 \x01(\x04R\n" +
	"writeBytes\"\x98\x02\n" +
	"\x06IOInfo\x12(\n" +
	"\x10total_read_bytes\x18\x01 \x01(\x04R\x0etotalReadBytes\x12*\n" +
	"\x11total_write_bytes\x18\x02 \x01(\x04R\x0ftotalWriteBytes\x12/\n" +
	"\x14total_net_recv_bytes\x18\x03 \x01(\x04R\x11totalNetRecvBytes\x12/\n" +
	"\x14total_net_sent_bytes\x18\x04 \x01(\x04R\x11totalNetSentBytes\x120\n" +
	"\bnetworks\x18\x05 \x03(\v2\x14.pb.NetworkInterfaceR\bnetworks\x12$\n" +
	"\x05disks\x18\x06 \x03(\v2\x0e.pb.DiskDeviceR\x05disks\"\xe8\x02\n" +
	"\tFaultInfo\x12\x1f\n" +
	"\vpage_faults\x18\x01 \x01(\x04R\n" +
	"pageFaults\x12!\n" +
	"\fmajor_faults\x18\x02 \x01(\x04R\vmajorFaults\x12!\n" +
	"\fminor_faults\x18\x03 \x01(\x04R\vminorFaults\x12&\n" +
	"\x0fpage_fault_rate\x18\x04 \x01(\x01R\rpageFaultRate\x12(\n" +
	"\x10major_fault_rate\x18\x05 \x01(\x01R\x0emajorFaultRate\x12(\n" +
	"\x10minor_fault_rate\x18\x06 \x01(\x01R\x0eminorFaultRate\x12\x17\n" +
	"\aswap_in\x18\a \x01(\x04R\x06swapIn\x12\x19\n" +
	"\bswap_out\x18\b \x01(\x04R\aswapOut\x12 \n" +
	"\fswap_in_rate\x18\t \x01(\x01R\n" +
	"swapInRate\x12\"\n" +
	"\rswap_out_rate\x18\n" +
	" \x01(\x01R\vswapOutRate\"\xe5\x01\n" +
	"\vSystemStats\x12)\n" +
	"\tprocesses\x18\x01 \x03(\v2\v.pb.ProcessR\tprocesses\x12!\n" +
	"\x04gpus\x18\x02 \x03(\v2\r.pb.GPUStatusR\x04gpus\x12\x1d\n" +
	"\x03cpu\x18\x03 \x01(\v2\v.pb.CPUInfoR\x03cpu\x12&\n" +
	"\x06memory\x18\x04 \x01(\v2\x0e.pb.MemoryInfoR\x06memory\x12\x1a\n" +
	"\x02io\x18\x05 \x01(\v2\n" +
	".pb.IOInfoR\x02io\x12%\n" +
	"\x06faults\x18\x06 \x01(\v2\r.pb.FaultInfoR\x06faults\"^\n" +
	"\x0eWrapperRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"\xbe\x01\n" +
	"\x0fWrapperResponse\x122\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1a.pb.WrapperResponse.ActionR\x06action\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0erewritten_args\x18\x03 \x03(\tR\rrewrittenArgs\"6\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\x12\v\n" +
	"\aREWRITE\x10\x02\x12\t\n" +
	"\x05ALERT\x10\x03\"8\n" +
	"\vProcessList\x12)\n" +
	"\tprocesses\x18\x01 \x03(\v2\v.pb.ProcessR\tprocesses*\xdb\x02\n" +
	"\tEventType\x12\n" +
	"\n" +
	"\x06EXECVE\x10\x00\x12\n" +
	"\n" +
	"\x06OPENAT\x10\x01\x12\x13\n" +
	"\x0fNETWORK_CONNECT\x10\x02\x12\t\n" +
	"\x05MKDIR\x10\x03\x12\n" +
	"\n" +
	"\x06UNLINK\x10\x04\x12\t\n" +
	"\x05IOCTL\x10\x05\x12\x10\n" +
	"\fNETWORK_BIND\x10\x06\x12\x12\n" +
	"\x0eNETWORK_SENDTO\x10\a\x12\x14\n" +
	"\x10NETWORK_RECVFROM\x10\b\x12\b\n" +
	"\x04READ\x10\t\x12\t\n" +
	"\x05WRITE\x10\n" +
	"\x12\b\n" +
	"\x04OPEN\x10\v\x12\t\n" +
	"\x05CHMOD\x10\f\x12\t\n" +
	"\x05CHOWN\x10\r\x12\n" +
	"\n" +
	"\x06RENAME\x10\x0e\x12\b\n" +
	"\x04LINK\x10\x0f\x12\v\n" +
	"\aSYMLINK\x10\x10\x12\t\n" +
	"\x05MKNOD\x10\x11\x12\t\n" +
	"\x05CLONE\x10\x12\x12\b\n" +
	"\x04EXIT\x10\x13\x12\n" +
	"\n" +
	"\x06SOCKET\x10\x14\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x15\x12\v\n" +
	"\aACCEPT4\x10\x16\x12\x15\n" +
	"\x11WRAPPER_INTERCEPT\x10\x17\x12\x0f\n" +
	"\vNATIVE_HOOK\x10\x18B\x16Z\x14agent-ebpf-filter/pbb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_tracker_proto_goTypes = []any{
	(EventType)(0),              // 0: pb.EventType
	(CPUInfo_Core_Type)(0),      // 1: pb.CPUInfo.Core.Type
	(WrapperResponse_Action)(0), // 2: pb.WrapperResponse.Action
	(*RegisterRequest)(nil),     // 3: pb.RegisterRequest
	(*RegisterResponse)(nil),    // 4: pb.RegisterResponse
	(*UnregisterRequest)(nil),   // 5: pb.UnregisterRequest
	(*UnregisterResponse)(nil),  // 6: pb.UnregisterResponse
	(*Event)(nil),               // 7: pb.Event
	(*EventBatch)(nil),          // 8: pb.EventBatch
	(*Process)(nil),             // 9: pb.Process
	(*GPUStatus)(nil),           // 10: pb.GPUStatus
	(*CPUInfo)(nil),             // 11: pb.CPUInfo
	(*MemoryInfo)(nil),          // 12: pb.MemoryInfo
	(*Hook)(nil),                // 13: pb.Hook
	(*HookRequest)(nil),         // 14: pb.HookRequest
	(*HookResponse)(nil),        // 15: pb.HookResponse
	(*NetworkInterface)(nil),    // 16: pb.NetworkInterface
	(*DiskDevice)(nil),          // 17: pb.DiskDevice
	(*IOInfo)(nil),              // 18: pb.IOInfo
	(*FaultInfo)(nil),           // 19: pb.FaultInfo
	(*SystemStats)(nil),         // 20: pb.SystemStats
	(*WrapperRequest)(nil),      // 21: pb.WrapperRequest
	(*WrapperResponse)(nil),     // 22: pb.WrapperResponse
	(*ProcessList)(nil),         // 23: pb.ProcessList
	(*CPUInfo_Core)(nil),        // 24: pb.CPUInfo.Core
}
var file_tracker_proto_depIdxs = []int32{
	0,  // 0: pb.Event.event_type:type_name -> pb.EventType
	7,  // 1: pb.EventBatch.events:type_name -> pb.Event
	24, // 2: pb.CPUInfo.core_details:type_name -> pb.CPUInfo.Core
	16, // 3: pb.IOInfo.networks:type_name -> pb.NetworkInterface
	17, // 4: pb.IOInfo.disks:type_name -> pb.DiskDevice
	9,  // 5: pb.SystemStats.processes:type_name -> pb.Process
	10, // 6: pb.SystemStats.gpus:type_name -> pb.GPUStatus
	11, // 7: pb.SystemStats.cpu:type_name -> pb.CPUInfo
	12, // 8: pb.SystemStats.memory:type_name -> pb.MemoryInfo
	18, // 9: pb.SystemStats.io:type_name -> pb.IOInfo
	19, // 10: pb.SystemStats.faults:type_name -> pb.FaultInfo
	2,  // 11: pb.WrapperResponse.action:type_name -> pb.WrapperResponse.Action
	9,  // 12: pb.ProcessList.processes:type_name -> pb.Process
	1,  // 13: pb.CPUInfo.Core.type:type_name -> pb.CPUInfo.Core.Type
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		EnumInfos:         file_tracker_proto_enumTypes,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
