// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WrapperResponse_Action int32

const (
	WrapperResponse_ALLOW   WrapperResponse_Action = 0
	WrapperResponse_BLOCK   WrapperResponse_Action = 1
	WrapperResponse_REWRITE WrapperResponse_Action = 2
	WrapperResponse_ALERT   WrapperResponse_Action = 3
)

// Enum value maps for WrapperResponse_Action.
var (
	WrapperResponse_Action_name = map[int32]string{
		0: "ALLOW",
		1: "BLOCK",
		2: "REWRITE",
		3: "ALERT",
	}
	WrapperResponse_Action_value = map[string]int32{
		"ALLOW":   0,
		"BLOCK":   1,
		"REWRITE": 2,
		"ALERT":   3,
	}
)

func (x WrapperResponse_Action) Enum() *WrapperResponse_Action {
	p := new(WrapperResponse_Action)
	*p = x
	return p
}

func (x WrapperResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WrapperResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_tracker_proto_enumTypes[0].Descriptor()
}

func (WrapperResponse_Action) Type() protoreflect.EnumType {
	return &file_tracker_proto_enumTypes[0]
}

func (x WrapperResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WrapperResponse_Action.Descriptor instead.
func (WrapperResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{9, 0}
}

// Represents a process registration request
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Represents a process registration response
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Represents a process unregistration request
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Represents a process unregistration response
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Represents an intercepted eBPF event (e.g., file open, exec)
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Event) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Event) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Event) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Event) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Represents system process information for the tree view
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float64                `protobuf:"fixed64,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           float32                `protobuf:"fixed32,5,opt,name=mem,proto3" json:"mem,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	GpuMem        uint32                 `protobuf:"varint,7,opt,name=gpu_mem,json=gpuMem,proto3" json:"gpu_mem,omitempty"`    // GPU VRAM usage in MiB
	GpuUtil       uint32                 `protobuf:"varint,8,opt,name=gpu_util,json=gpuUtil,proto3" json:"gpu_util,omitempty"` // GPU utilization percentage
	GpuId         uint32                 `protobuf:"varint,9,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`       // GPU index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Process) GetMem() float32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetGpuMem() uint32 {
	if x != nil {
		return x.GpuMem
	}
	return 0
}

func (x *Process) GetGpuUtil() uint32 {
	if x != nil {
		return x.GpuUtil
	}
	return 0
}

func (x *Process) GetGpuId() uint32 {
	if x != nil {
		return x.GpuId
	}
	return 0
}

type GPUStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UtilGpu       uint32                 `protobuf:"varint,3,opt,name=util_gpu,json=utilGpu,proto3" json:"util_gpu,omitempty"`
	UtilMem       uint32                 `protobuf:"varint,4,opt,name=util_mem,json=utilMem,proto3" json:"util_mem,omitempty"`
	MemTotal      uint32                 `protobuf:"varint,5,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       uint32                 `protobuf:"varint,6,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	Temp          uint32                 `protobuf:"varint,7,opt,name=temp,proto3" json:"temp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUStatus) Reset() {
	*x = GPUStatus{}
	mi := &file_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatus) ProtoMessage() {}

func (x *GPUStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatus.ProtoReflect.Descriptor instead.
func (*GPUStatus) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *GPUStatus) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUStatus) GetUtilGpu() uint32 {
	if x != nil {
		return x.UtilGpu
	}
	return 0
}

func (x *GPUStatus) GetUtilMem() uint32 {
	if x != nil {
		return x.UtilMem
	}
	return 0
}

func (x *GPUStatus) GetMemTotal() uint32 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *GPUStatus) GetMemUsed() uint32 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *GPUStatus) GetTemp() uint32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

type SystemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	Gpus          []*GPUStatus           `protobuf:"bytes,2,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *SystemStats) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *SystemStats) GetGpus() []*GPUStatus {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type WrapperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperRequest) Reset() {
	*x = WrapperRequest{}
	mi := &file_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperRequest) ProtoMessage() {}

func (x *WrapperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperRequest.ProtoReflect.Descriptor instead.
func (*WrapperRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *WrapperRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WrapperRequest) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *WrapperRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WrapperRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type WrapperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WrapperResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=pb.WrapperResponse_Action" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RewrittenArgs []string               `protobuf:"bytes,3,rep,name=rewritten_args,json=rewrittenArgs,proto3" json:"rewritten_args,omitempty"` // Only if action is REWRITE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperResponse) Reset() {
	*x = WrapperResponse{}
	mi := &file_tracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperResponse) ProtoMessage() {}

func (x *WrapperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperResponse.ProtoReflect.Descriptor instead.
func (*WrapperResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{9}
}

func (x *WrapperResponse) GetAction() WrapperResponse_Action {
	if x != nil {
		return x.Action
	}
	return WrapperResponse_ALLOW
}

func (x *WrapperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WrapperResponse) GetRewrittenArgs() []string {
	if x != nil {
		return x.RewrittenArgs
	}
	return nil
}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_tracker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessList) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\x02pb\"#\n" +
	"\x0fRegisterRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x11UnregisterRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x05Event\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\"\xc6\x01\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x05 \x01(\x02R\x03mem\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x17\n" +
	"\agpu_mem\x18\a \x01(\rR\x06gpuMem\x12\x19\n" +
	"\bgpu_util\x18\b \x01(\rR\agpuUtil\x12\x15\n" +
	"\x06gpu_id\x18\t \x01(\rR\x05gpuId\"\xb7\x01\n" +
	"\tGPUStatus\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\butil_gpu\x18\x03 \x01(\rR\autilGpu\x12\x19\n" +
	"\butil_mem\x18\x04 \x01(\rR\autilMem\x12\x1b\n" +
	"\tmem_total\x18\x05 \x01(\rR\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x06 \x01(\rR\amemUsed\x12\x12\n" +
	"\x04temp\x18\a \x01(\rR\x04temp\"[\n" +
	"\vSystemStats\x12)\n" +
	"\tprocesses\x18\x01 \x03(\v2\v.pb.ProcessR\tprocesses\x12!\n" +
	"\x04gpus\x18\x02 \x03(\v2\r.pb.GPUStatusR\x04gpus\"^\n" +
	"\x0eWrapperRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"\xbe\x01\n" +
	"\x0fWrapperResponse\x122\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1a.pb.WrapperResponse.ActionR\x06action\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0erewritten_args\x18\x03 \x03(\tR\rrewrittenArgs\"6\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\x12\v\n" +
	"\aREWRITE\x10\x02\x12\t\n" +
	"\x05ALERT\x10\x03\"8\n" +
	"\vProcessList\x12)\n" +
	"\tprocesses\x18\x01 \x03(\v2\v.pb.ProcessR\tprocessesB\x16Z\x14agent-ebpf-filter/pbb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tracker_proto_goTypes = []any{
	(WrapperResponse_Action)(0), // 0: pb.WrapperResponse.Action
	(*RegisterRequest)(nil),     // 1: pb.RegisterRequest
	(*RegisterResponse)(nil),    // 2: pb.RegisterResponse
	(*UnregisterRequest)(nil),   // 3: pb.UnregisterRequest
	(*UnregisterResponse)(nil),  // 4: pb.UnregisterResponse
	(*Event)(nil),               // 5: pb.Event
	(*Process)(nil),             // 6: pb.Process
	(*GPUStatus)(nil),           // 7: pb.GPUStatus
	(*SystemStats)(nil),         // 8: pb.SystemStats
	(*WrapperRequest)(nil),      // 9: pb.WrapperRequest
	(*WrapperResponse)(nil),     // 10: pb.WrapperResponse
	(*ProcessList)(nil),         // 11: pb.ProcessList
}
var file_tracker_proto_depIdxs = []int32{
	6, // 0: pb.SystemStats.processes:type_name -> pb.Process
	7, // 1: pb.SystemStats.gpus:type_name -> pb.GPUStatus
	0, // 2: pb.WrapperResponse.action:type_name -> pb.WrapperResponse.Action
	6, // 3: pb.ProcessList.processes:type_name -> pb.Process
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		EnumInfos:         file_tracker_proto_enumTypes,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
