[package]
name = "agent-wrapper"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
agent-common = { path = "../agent-common" }
agent-proto = { path = "../agent-proto" }
anyhow.workspace = true
clap.workspace = true
nix.workspace = true
prost.workspace = true
