# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker_shell.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tracker_shell.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tracker_shell.proto\x12\x02pb\"\x83\x01\n\x0cShellSession\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x0c\n\x04\x63ols\x18\x06 \x01(\t\x12\x0c\n\x04rows\x18\x07 \x01(\t\x12\x0b\n\x03\x63wd\x18\x08 \x01(\t\"6\n\x10ShellSessionList\x12\"\n\x08sessions\x18\x01 \x03(\x0b\x32\x10.pb.ShellSession\"I\n\x19ShellSessionCreateRequest\x12\x0f\n\x07workdir\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\r\n\x05label\x18\x03 \x01(\t\"j\n\tFileEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06is_dir\x18\x02 \x01(\x08\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\x10\n\x08mod_time\x18\x06 \x01(\t\"^\n\x10\x46ileListResponse\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.pb.FileEntry\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\"z\n\x13\x46ilePreviewResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\x10\n\x08mod_time\x18\x05 \x01(\t\x12\x11\n\ttruncated\x18\x06 \x01(\x08\x42\x16Z\x14\x61gent-ebpf-filter/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_shell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024agent-ebpf-filter/pb'
  _globals['_SHELLSESSION']._serialized_start=28
  _globals['_SHELLSESSION']._serialized_end=159
  _globals['_SHELLSESSIONLIST']._serialized_start=161
  _globals['_SHELLSESSIONLIST']._serialized_end=215
  _globals['_SHELLSESSIONCREATEREQUEST']._serialized_start=217
  _globals['_SHELLSESSIONCREATEREQUEST']._serialized_end=290
  _globals['_FILEENTRY']._serialized_start=292
  _globals['_FILEENTRY']._serialized_end=398
  _globals['_FILELISTRESPONSE']._serialized_start=400
  _globals['_FILELISTRESPONSE']._serialized_end=494
  _globals['_FILEPREVIEWRESPONSE']._serialized_start=496
  _globals['_FILEPREVIEWRESPONSE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
