root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./backend/agent-ebpf-filter"
  cmd = "cd backend/ebpf && go generate && cd .. && go build -o agent-ebpf-filter ."
  delay = 1000
  exclude_dir = ["frontend", "adapters", "docs", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go", "_bpfeb.go", "_bpfel.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["backend", "proto"]
  include_ext = ["go", "proto", "c", "h"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
