package main

import (
	"encoding/json"
	"fmt"
	"os"
)

// 决策树编译器：将训练好的决策树编译为 eBPF C 代码

type TreeNode struct {
	FeatureIdx int     `json:"feature_idx"`
	Threshold  float64 `json:"threshold"`
	LeftChild  int     `json:"left_child"`  // -1 表示叶节点
	RightChild int     `json:"right_child"` // -1 表示叶节点
	LeafValue  int     `json:"leaf_value"`  // 叶节点的预测值 (0=ALLOW, 1=BLOCK, 2=ALERT)
	IsLeaf     bool    `json:"is_leaf"`
}

type DecisionTree struct {
	Nodes    []TreeNode `json:"nodes"`
	MaxDepth int        `json:"max_depth"`
}

type RandomForest struct {
	Trees    []DecisionTree `json:"trees"`
	NumTrees int            `json:"num_trees"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: go run compile_ebpf_model.go <model.json>")
		os.Exit(1)
	}

	// 读取模型 JSON
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Printf("Error reading model: %v\n", err)
		os.Exit(1)
	}

	var forest RandomForest
	if err := json.Unmarshal(data, &forest); err != nil {
		fmt.Printf("Error parsing model: %v\n", err)
		os.Exit(1)
	}

	// 生成 eBPF C 代码
	ebpfCode := generateEBPFCode(forest)

	// 写入文件
	outputPath := "../ebpf/_ml_model_ebpf.c"
	if err := os.WriteFile(outputPath, []byte(ebpfCode), 0644); err != nil {
		fmt.Printf("Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ eBPF model generated: %s\n", outputPath)
	fmt.Printf("📊 Model stats:\n")
	fmt.Printf("  - Trees: %d\n", forest.NumTrees)
	totalNodes := 0
	for _, tree := range forest.Trees {
		totalNodes += len(tree.Nodes)
	}
	fmt.Printf("  - Total nodes: %d\n", totalNodes)
	fmt.Printf("  - Estimated memory: %d KB\n", (totalNodes*24)/1024)
}

func generateEBPFCode(forest RandomForest) string {
	code := `// Auto-generated eBPF ML model
// DO NOT EDIT - Generated by compile_ebpf_model.go

#include <linux/bpf.h>
#include <linux/types.h>
#include <bpf/bpf_helpers.h>

#define FEATURE_DIM 128
#define NUM_TREES ` + fmt.Sprintf("%d", forest.NumTrees) + `

// 定点数精度 (1000 = 0.001 精度)
#define FLOAT_SCALE 1000
#define FLOAT_TO_FIXED(f) ((__s64)((f) * FLOAT_SCALE))

// 决策树节点结构
struct tree_node {
    __u32 feature_idx;
    __s64 threshold;      // 定点数
    __s32 left_child;     // -1 = 叶节点
    __s32 right_child;
    __s32 leaf_value;     // 0=ALLOW, 1=BLOCK, 2=ALERT
    __u8 is_leaf;
};

// Action types
#define ACTION_ALLOW 0
#define ACTION_BLOCK 1
#define ACTION_ALERT 2

`

	// 生成每棵树的节点数据
	totalNodes := 0
	for treeIdx, tree := range forest.Trees {
		code += fmt.Sprintf("\n// Tree %d (%d nodes)\n", treeIdx, len(tree.Nodes))
		code += fmt.Sprintf("static const struct tree_node tree_%d_nodes[] = {\n", treeIdx)

		for _, node := range tree.Nodes {
			threshold := int64(node.Threshold * 1000) // 转换为定点数
			isLeaf := 0
			if node.IsLeaf {
				isLeaf = 1
			}

			code += fmt.Sprintf("    {%d, %d, %d, %d, %d, %d},\n",
				node.FeatureIdx, threshold, node.LeftChild, node.RightChild, node.LeafValue, isLeaf)
		}

		code += "};\n"
		totalNodes += len(tree.Nodes)
	}

	// 生成树评估函数
	code += `
// 评估单棵决策树
static __always_inline __s32 evaluate_tree(const struct tree_node *nodes, __s64 *features, __u32 num_nodes) {
    __u32 node_idx = 0;

    #pragma unroll
    for (int depth = 0; depth < 20; depth++) {  // 最大深度 20
        if (node_idx >= num_nodes) return ACTION_ALLOW;

        const struct tree_node *node = &nodes[node_idx];

        if (node->is_leaf) {
            return node->leaf_value;
        }

        __u32 feat_idx = node->feature_idx;
        if (feat_idx >= FEATURE_DIM) return ACTION_ALLOW;

        __s64 feat_val = features[feat_idx];

        if (feat_val <= node->threshold) {
            node_idx = node->left_child;
        } else {
            node_idx = node->right_child;
        }
    }

    return ACTION_ALLOW;  // 默认允许
}

// 随机森林预测
static __always_inline __s32 predict_random_forest(__s64 *features) {
    __u32 votes[3] = {0, 0, 0};  // ALLOW, BLOCK, ALERT

`

	// 展开每棵树的评估
	for treeIdx := range forest.Trees {
		code += fmt.Sprintf("    {\n")
		code += fmt.Sprintf("        __s32 pred = evaluate_tree(tree_%d_nodes, features, sizeof(tree_%d_nodes)/sizeof(struct tree_node));\n",
			treeIdx, treeIdx)
		code += fmt.Sprintf("        if (pred >= 0 && pred < 3) votes[pred]++;\n")
		code += fmt.Sprintf("    }\n")
	}

	code += `
    // 多数投票
    __s32 max_votes = votes[0];
    __s32 prediction = ACTION_ALLOW;

    if (votes[1] > max_votes) {
        max_votes = votes[1];
        prediction = ACTION_BLOCK;
    }
    if (votes[2] > max_votes) {
        prediction = ACTION_ALERT;
    }

    return prediction;
}

// BPF Map 存储特征 (避免栈溢出)
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, __s64[FEATURE_DIM]);
} feature_map SEC(".maps");

// eBPF 程序入口点示例
SEC("kprobe/sys_execve")
int ml_predict_syscall(struct pt_regs *ctx) {
    __u32 key = 0;
    __s64 *features = bpf_map_lookup_elem(&feature_map, &key);
    if (!features) {
        return 0;
    }

    // 初始化特征为 0
    #pragma unroll
    for (int i = 0; i < FEATURE_DIM; i++) {
        features[i] = 0;
    }

    // TODO: 从 ctx 提取特征
    // 这里需要根据实际的 syscall 上下文提取特征

    __s32 action = predict_random_forest(features);

    // 根据预测结果采取行动
    if (action == ACTION_BLOCK) {
        bpf_printk("ML Model: BLOCK action detected\n");
        return -1;  // 阻止系统调用
    }

    return 0;  // 允许
}

char LICENSE[] SEC("license") = "GPL";
`

	return code
}
