package network

// ---- moved from backend/zz_merged_backend.go section syscallsnetworkext.go ----

func syscallNameExtended(nr uint32) string {
	switch {
	case nr <= 200:
		return ""
	case nr <= 453:
		return syscallNameHigh(nr)
	default:
		return ""
	}
}

func syscallNameHigh(nr uint32) string {
	switch nr {
	case 201:
		return "time"
	case 202:
		return "futex"
	case 203:
		return "sched_setaffinity"
	case 204:
		return "sched_getaffinity"
	case 206:
		return "io_setup"
	case 207:
		return "io_destroy"
	case 208:
		return "io_getevents"
	case 209:
		return "io_submit"
	case 210:
		return "io_cancel"
	case 212:
		return "lookup_dcookie"
	case 213:
		return "epoll_create"
	case 216:
		return "remap_file_pages"
	case 217:
		return "getdents64"
	case 218:
		return "set_tid_address"
	case 219:
		return "restart_syscall"
	case 220:
		return "semtimedop"
	case 221:
		return "fadvise64"
	case 222:
		return "timer_create"
	case 223:
		return "timer_settime"
	case 224:
		return "timer_gettime"
	case 225:
		return "timer_getoverrun"
	case 226:
		return "timer_delete"
	case 227:
		return "clock_settime"
	case 228:
		return "clock_gettime"
	case 229:
		return "clock_getres"
	case 230:
		return "clock_nanosleep"
	case 231:
		return "exit_group"
	case 232:
		return "epoll_wait"
	case 233:
		return "epoll_ctl"
	case 234:
		return "tgkill"
	case 235:
		return "utimes"
	case 237:
		return "mbind"
	case 238:
		return "set_mempolicy"
	case 239:
		return "get_mempolicy"
	case 240:
		return "mq_open"
	case 241:
		return "mq_unlink"
	case 242:
		return "mq_timedsend"
	case 243:
		return "mq_timedreceive"
	case 244:
		return "mq_notify"
	case 245:
		return "mq_getsetattr"
	case 246:
		return "kexec_load"
	case 247:
		return "waitid"
	case 248:
		return "add_key"
	case 249:
		return "request_key"
	case 250:
		return "keyctl"
	case 251:
		return "ioprio_set"
	case 252:
		return "ioprio_get"
	case 253:
		return "inotify_init"
	case 254:
		return "inotify_add_watch"
	case 255:
		return "inotify_rm_watch"
	case 256:
		return "migrate_pages"
	case 257:
		return "openat"
	case 258:
		return "mkdirat"
	case 259:
		return "mknodat"
	case 260:
		return "fchownat"
	case 261:
		return "futimesat"
	case 262:
		return "newfstatat"
	case 263:
		return "unlinkat"
	case 264:
		return "renameat"
	case 265:
		return "linkat"
	case 266:
		return "symlinkat"
	case 267:
		return "readlinkat"
	case 268:
		return "fchmodat"
	case 269:
		return "faccessat"
	case 270:
		return "pselect6"
	case 271:
		return "ppoll"
	case 272:
		return "unshare"
	case 273:
		return "set_robust_list"
	case 274:
		return "get_robust_list"
	case 275:
		return "splice"
	case 276:
		return "tee"
	case 277:
		return "sync_file_range"
	case 278:
		return "vmsplice"
	case 279:
		return "move_pages"
	case 280:
		return "utimensat"
	case 281:
		return "epoll_pwait"
	case 282:
		return "signalfd"
	case 283:
		return "timerfd_create"
	case 284:
		return "eventfd"
	case 285:
		return "fallocate"
	case 286:
		return "timerfd_settime"
	case 287:
		return "timerfd_gettime"
	case 288:
		return "accept4"
	case 289:
		return "signalfd4"
	case 290:
		return "eventfd2"
	case 291:
		return "epoll_create1"
	case 292:
		return "dup3"
	case 293:
		return "pipe2"
	case 294:
		return "inotify_init1"
	case 295:
		return "preadv"
	case 296:
		return "pwritev"
	case 297:
		return "rt_tgsigqueueinfo"
	case 298:
		return "perf_event_open"
	case 299:
		return "recvmmsg"
	case 300:
		return "fanotify_init"
	case 301:
		return "fanotify_mark"
	case 302:
		return "prlimit64"
	case 303:
		return "name_to_handle_at"
	case 304:
		return "open_by_handle_at"
	case 305:
		return "clock_adjtime"
	case 306:
		return "syncfs"
	case 307:
		return "sendmmsg"
	case 308:
		return "setns"
	case 309:
		return "getcpu"
	case 310:
		return "process_vm_readv"
	case 311:
		return "process_vm_writev"
	case 312:
		return "kcmp"
	case 313:
		return "finit_module"
	case 314:
		return "sched_setattr"
	case 315:
		return "sched_getattr"
	case 316:
		return "renameat2"
	case 317:
		return "seccomp"
	case 318:
		return "getrandom"
	case 319:
		return "memfd_create"
	case 320:
		return "kexec_file_load"
	case 321:
		return "bpf"
	case 322:
		return "execveat"
	case 323:
		return "userfaultfd"
	case 324:
		return "membarrier"
	case 325:
		return "mlock2"
	case 326:
		return "copy_file_range"
	case 327:
		return "preadv2"
	case 328:
		return "pwritev2"
	case 329:
		return "pkey_mprotect"
	case 330:
		return "pkey_alloc"
	case 331:
		return "pkey_free"
	case 332:
		return "statx"
	case 333:
		return "io_pgetevents"
	case 334:
		return "rseq"
	case 424:
		return "pidfd_send_signal"
	case 425:
		return "io_uring_setup"
	case 426:
		return "io_uring_enter"
	case 427:
		return "io_uring_register"
	case 428:
		return "open_tree"
	case 429:
		return "move_mount"
	case 430:
		return "fsopen"
	case 431:
		return "fsconfig"
	case 432:
		return "fsmount"
	case 433:
		return "fspick"
	case 434:
		return "pidfd_open"
	case 435:
		return "clone3"
	case 436:
		return "close_range"
	case 437:
		return "openat2"
	case 438:
		return "pidfd_getfd"
	case 439:
		return "faccessat2"
	case 440:
		return "process_madvise"
	case 441:
		return "epoll_pwait2"
	case 442:
		return "mount_setattr"
	case 443:
		return "quotactl_fd"
	case 444:
		return "landlock_create_ruleset"
	case 445:
		return "landlock_add_rule"
	case 446:
		return "landlock_restrict_self"
	case 447:
		return "memfd_secret"
	case 448:
		return "process_mrelease"
	case 449:
		return "futex_waitv"
	case 450:
		return "set_mempolicy_home_node"
	case 451:
		return "cachestat"
	case 452:
		return "fchmodat2"
	case 453:
		return "map_shadow_stack"
	}
	return ""
}
