package app

// ---- moved from backend/zz_merged_backend.go section syscalls_network.go ----

func syscallName(nr uint32) string {
	if name := syscallNameHigh(nr); name != "" {
		return name
	}
	switch nr {
	case 0:
		return "read"
	case 1:
		return "write"
	case 2:
		return "open"
	case 3:
		return "close"
	case 4:
		return "stat"
	case 5:
		return "fstat"
	case 6:
		return "lstat"
	case 7:
		return "poll"
	case 8:
		return "lseek"
	case 9:
		return "mmap"
	case 10:
		return "mprotect"
	case 11:
		return "munmap"
	case 12:
		return "brk"
	case 13:
		return "rt_sigaction"
	case 14:
		return "rt_sigprocmask"
	case 16:
		return "ioctl"
	case 17:
		return "pread64"
	case 18:
		return "pwrite64"
	case 19:
		return "readv"
	case 20:
		return "writev"
	case 21:
		return "access"
	case 22:
		return "pipe"
	case 23:
		return "select"
	case 24:
		return "sched_yield"
	case 25:
		return "mremap"
	case 26:
		return "msync"
	case 27:
		return "mincore"
	case 28:
		return "madvise"
	case 29:
		return "shmget"
	case 30:
		return "shmat"
	case 31:
		return "shmctl"
	case 32:
		return "dup"
	case 33:
		return "dup2"
	case 34:
		return "pause"
	case 35:
		return "nanosleep"
	case 36:
		return "getitimer"
	case 37:
		return "alarm"
	case 38:
		return "setitimer"
	case 39:
		return "getpid"
	case 40:
		return "sendfile"
	case 41:
		return "socket"
	case 42:
		return "connect"
	case 43:
		return "accept"
	case 44:
		return "sendto"
	case 45:
		return "recvfrom"
	case 46:
		return "sendmsg"
	case 47:
		return "recvmsg"
	case 48:
		return "shutdown"
	case 49:
		return "bind"
	case 50:
		return "listen"
	case 51:
		return "getsockname"
	case 52:
		return "getpeername"
	case 53:
		return "socketpair"
	case 54:
		return "setsockopt"
	case 55:
		return "getsockopt"
	case 56:
		return "clone"
	case 57:
		return "fork"
	case 58:
		return "vfork"
	case 59:
		return "execve"
	case 60:
		return "exit"
	case 61:
		return "wait4"
	case 62:
		return "kill"
	case 63:
		return "uname"
	case 64:
		return "semget"
	case 65:
		return "semop"
	case 66:
		return "semctl"
	case 67:
		return "shmdt"
	case 68:
		return "msgget"
	case 69:
		return "msgsnd"
	case 70:
		return "msgrcv"
	case 71:
		return "msgctl"
	case 72:
		return "fcntl"
	case 73:
		return "flock"
	case 74:
		return "fsync"
	case 75:
		return "fdatasync"
	case 76:
		return "truncate"
	case 77:
		return "ftruncate"
	case 78:
		return "getdents"
	case 79:
		return "getcwd"
	case 80:
		return "chdir"
	case 81:
		return "fchdir"
	case 82:
		return "rename"
	case 83:
		return "mkdir"
	case 84:
		return "rmdir"
	case 85:
		return "creat"
	case 86:
		return "link"
	case 87:
		return "unlink"
	case 88:
		return "symlink"
	case 89:
		return "readlink"
	case 90:
		return "chmod"
	case 91:
		return "fchmod"
	case 92:
		return "chown"
	case 93:
		return "fchown"
	case 94:
		return "lchown"
	case 95:
		return "umask"
	case 96:
		return "gettimeofday"
	case 97:
		return "getrlimit"
	case 98:
		return "getrusage"
	case 99:
		return "sysinfo"
	case 100:
		return "times"
	case 101:
		return "ptrace"
	case 102:
		return "getuid"
	case 103:
		return "syslog"
	case 104:
		return "getgid"
	case 105:
		return "setuid"
	case 106:
		return "setgid"
	case 107:
		return "geteuid"
	case 108:
		return "getegid"
	case 109:
		return "setpgid"
	case 110:
		return "getppid"
	case 111:
		return "getpgrp"
	case 112:
		return "setsid"
	case 113:
		return "setreuid"
	case 114:
		return "setregid"
	case 115:
		return "getgroups"
	case 116:
		return "setgroups"
	case 117:
		return "setresuid"
	case 118:
		return "getresuid"
	case 119:
		return "setresgid"
	case 120:
		return "getresgid"
	case 121:
		return "getpgid"
	case 122:
		return "setfsuid"
	case 123:
		return "setfsgid"
	case 124:
		return "getsid"
	case 125:
		return "capget"
	case 126:
		return "capset"
	case 127:
		return "rt_sigpending"
	case 128:
		return "rt_sigtimedwait"
	case 129:
		return "rt_sigqueueinfo"
	case 130:
		return "rt_sigsuspend"
	case 131:
		return "sigaltstack"
	case 132:
		return "utime"
	case 133:
		return "mknod"
	case 135:
		return "personality"
	case 136:
		return "ustat"
	case 137:
		return "statfs"
	case 138:
		return "fstatfs"
	case 139:
		return "sysfs"
	case 140:
		return "getpriority"
	case 141:
		return "setpriority"
	case 142:
		return "sched_setparam"
	case 143:
		return "sched_getparam"
	case 144:
		return "sched_setscheduler"
	case 145:
		return "sched_getscheduler"
	case 146:
		return "sched_get_priority_max"
	case 147:
		return "sched_get_priority_min"
	case 148:
		return "sched_rr_get_interval"
	case 149:
		return "mlock"
	case 150:
		return "munlock"
	case 151:
		return "mlockall"
	case 152:
		return "munlockall"
	case 153:
		return "vhangup"
	case 154:
		return "modify_ldt"
	case 155:
		return "pivot_root"
	case 157:
		return "prctl"
	case 158:
		return "arch_prctl"
	case 159:
		return "adjtimex"
	case 160:
		return "setrlimit"
	case 161:
		return "chroot"
	case 162:
		return "sync"
	case 163:
		return "acct"
	case 164:
		return "settimeofday"
	case 165:
		return "mount"
	case 166:
		return "umount2"
	case 167:
		return "swapon"
	case 168:
		return "swapoff"
	case 169:
		return "reboot"
	case 170:
		return "sethostname"
	case 171:
		return "setdomainname"
	case 172:
		return "iopl"
	case 173:
		return "ioperm"
	case 175:
		return "init_module"
	case 176:
		return "delete_module"
	case 179:
		return "quotactl"
	case 186:
		return "gettid"
	case 187:
		return "readahead"
	case 188:
		return "setxattr"
	case 189:
		return "lsetxattr"
	case 190:
		return "fsetxattr"
	case 191:
		return "getxattr"
	case 192:
		return "lgetxattr"
	case 193:
		return "fgetxattr"
	case 194:
		return "listxattr"
	case 195:
		return "llistxattr"
	case 196:
		return "flistxattr"
	case 197:
		return "removexattr"
	case 198:
		return "lremovexattr"
	case 199:
		return "fremovexattr"
	case 200:
		return "tkill"
	}
	return ""
}
