#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHELL_ENV_FILE="${DEV_ENV_FILE:-$ROOT/.env.dev}"
MAKE_ENV_FILE="${DEV_ENV_MAKEFILE:-$ROOT/.env.dev.mk}"

CONFIG_KEYS=(
  DISABLE_AUTH
  GIN_MODE
  AGENT_EBPF_DEV_SESSION
  AGENT_WRAPPER_PATH
  CONTAINER_CLI
  DEV_BRANCH
  DEV_IMAGE_REPOSITORY
  DEV_IMAGE_TAG
  DEV_IMAGE
  DEV_CONTAINER
  DEV_WORKSPACE
  DEVCONTAINER_POSTCREATE_INSTALL
  CUDA_GO_TAGS
  OS_SMOKE_PRIVILEGE_CMD
)

usage() {
  cat <<USAGE
Usage: $0 [configure|print|doctor|reset|defaults|help]

Commands:
  configure  Run the interactive development environment wizard (default)
  print      Print shell exports for the current config
  doctor     Show effective config and check common dev tools
  reset      Remove generated development env files
  defaults   Write recommended local defaults without prompting
USAGE
}

shell_quote() {
  local value="$1"
  printf "'"
  printf "%s" "$value" | sed "s/'/'\\\\''/g"
  printf "'"
}

make_escape() {
  local value="$1"
  value="${value//'$'/'$$'}"
  value="${value//'#'/'\#'}"
  value="${value//$'\n'/ }"
  printf "%s" "$value"
}

load_existing() {
  if [ -f "$SHELL_ENV_FILE" ]; then
    # Local developer-controlled file generated by this script.
    set -a
    # shellcheck disable=SC1090
    . "$SHELL_ENV_FILE"
    set +a
  fi
}

detect_container_cli() {
  if command -v docker >/dev/null 2>&1; then
    printf docker
  elif command -v podman >/dev/null 2>&1; then
    printf podman
  fi
}

detect_branch() {
  git -C "$ROOT" branch --show-current 2>/dev/null || true
}

detect_owner_repo() {
  git -C "$ROOT" remote get-url origin 2>/dev/null \
    | sed -E 's#^(git@github.com:|https://github.com/|ssh://git@github.com/)##; s#\.git$##' \
    | tr '[:upper:]' '[:lower:]' || true
}

branch_tag() {
  local branch="$1"
  local base suffix prefix
  base="$(printf '%s' "$branch" | sed -E 's#[^A-Za-z0-9_.-]+#-#g; s#^-+##; s#-+$##')"
  [ -n "$base" ] || base=local
  suffix="$(printf '%s' "$branch" | sha256sum | cut -c1-12)"
  prefix="$(printf '%s' "$base" | cut -c1-115 | sed -E 's#-+$##')"
  [ -n "$prefix" ] || prefix=local
  printf '%s-%s' "$prefix" "$suffix"
}

cuda_default() {
  if [ -x /opt/cuda/bin/nvcc ] && [ -r /opt/cuda/lib64/libcudart.so ]; then
    printf cuda
  fi
}

get_var() {
  local key="$1"
  printf '%s' "${!key-}"
}

set_var() {
  local key="$1" value="$2"
  printf -v "$key" '%s' "$value"
}

prompt_value() {
  local key="$1" label="$2" default_value="${3:-}" hint="${4:-}"
  local current answer shown
  current="$(get_var "$key")"
  if [ -n "$current" ]; then
    shown="$current"
  else
    shown="$default_value"
  fi
  printf '\n%s\n' "$label"
  [ -n "$hint" ] && printf '  %s\n' "$hint"
  if [ -n "$shown" ]; then
    printf '  [%s] > ' "$shown"
  else
    printf '  [auto/unset] > '
  fi
  IFS= read -r answer
  case "$answer" in
    "") [ -n "$shown" ] && set_var "$key" "$shown" || set_var "$key" "" ;;
    "-") set_var "$key" "" ;;
    *) set_var "$key" "$answer" ;;
  esac
}

write_files() {
  local generated_at
  generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  {
    printf '# Generated by scripts/dev-env.sh at %s\n' "$generated_at"
    printf '# Source this file for shell sessions: set -a; . ./.env.dev; set +a\n'
    for key in "${CONFIG_KEYS[@]}"; do
      local value
      value="$(get_var "$key")"
      [ -n "$value" ] || continue
      printf 'export %s=%s\n' "$key" "$(shell_quote "$value")"
    done
  } > "$SHELL_ENV_FILE"

  {
    printf '# Generated by scripts/dev-env.sh at %s\n' "$generated_at"
    printf '# Included automatically by Makefile when present.\n'
    for key in "${CONFIG_KEYS[@]}"; do
      local value
      value="$(get_var "$key")"
      [ -n "$value" ] || continue
      printf '%s := %s\n' "$key" "$(make_escape "$value")"
    done
  } > "$MAKE_ENV_FILE"

  printf '\nWrote:\n  %s\n  %s\n' "${SHELL_ENV_FILE#$ROOT/}" "${MAKE_ENV_FILE#$ROOT/}"
}

apply_recommended_defaults() {
  : "${DISABLE_AUTH:=true}"
  : "${GIN_MODE:=debug}"
  : "${AGENT_EBPF_DEV_SESSION:=agent-ebpf-dev}"
  : "${DEV_CONTAINER:=agent-ebpf-filiter-dev}"
  : "${DEV_WORKSPACE:=/workspaces/agent-ebpf-filiter}"
  : "${DEVCONTAINER_POSTCREATE_INSTALL:=0}"
}

configure() {
  if [ ! -t 0 ]; then
    echo "Interactive configuration requires a TTY. Use '$0 defaults' for non-interactive defaults." >&2
    exit 2
  fi
  load_existing
  apply_recommended_defaults

  local detected_container detected_branch detected_owner detected_repo detected_tag detected_cuda
  detected_container="$(detect_container_cli)"
  detected_branch="$(detect_branch)"
  detected_owner="$(detect_owner_repo)"
  detected_repo=""
  [ -n "$detected_owner" ] && detected_repo="ghcr.io/${detected_owner}/devcontainer"
  detected_tag=""
  [ -n "$detected_branch" ] && detected_tag="$(branch_tag "$detected_branch")"
  detected_cuda="$(cuda_default)"

  cat <<INTRO
Interactive dev env configuration

Files generated:
  .env.dev     - shell exports for direct script use
  .env.dev.mk  - Makefile variables loaded by make targets

Press Enter to accept the shown value. Enter '-' to unset a value.
INTRO

  prompt_value DISABLE_AUTH "Disable auth for local dev backend?" "${DISABLE_AUTH:-true}" "Use true for make dev; release installs still use runtime config."
  prompt_value GIN_MODE "Gin mode for dev backend" "${GIN_MODE:-debug}" "debug or release; debug is recommended while developing."
  prompt_value AGENT_EBPF_DEV_SESSION "Zellij session name" "${AGENT_EBPF_DEV_SESSION:-agent-ebpf-dev}" "Used by make dev / scripts/dev-zellij.sh."
  prompt_value AGENT_WRAPPER_PATH "Wrapper path override" "${AGENT_WRAPPER_PATH:-}" "Leave unset to use ./agent-wrapper built by make dev."

  prompt_value CONTAINER_CLI "Container CLI override" "${CONTAINER_CLI:-$detected_container}" "docker or podman; leave unset to let Makefile auto-detect."
  prompt_value DEV_BRANCH "Devcontainer branch override" "${DEV_BRANCH:-}" "Detected branch: ${detected_branch:-unknown}. Leave unset for Makefile auto-detect."
  prompt_value DEV_IMAGE_REPOSITORY "GHCR devcontainer repository override" "${DEV_IMAGE_REPOSITORY:-}" "Detected repository: ${detected_repo:-unknown}. Leave unset for Makefile auto-detect."
  prompt_value DEV_IMAGE_TAG "GHCR devcontainer image tag override" "${DEV_IMAGE_TAG:-}" "Detected tag for current branch: ${detected_tag:-unknown}. Leave unset for Makefile auto-detect."
  prompt_value DEV_IMAGE "Full devcontainer image override" "${DEV_IMAGE:-}" "Usually leave unset so repository/tag are derived."
  prompt_value DEV_CONTAINER "Local devcontainer name" "${DEV_CONTAINER:-agent-ebpf-filiter-dev}" "Used by make exec."
  prompt_value DEV_WORKSPACE "Path inside devcontainer" "${DEV_WORKSPACE:-/workspaces/agent-ebpf-filiter}" "Keep aligned with .devcontainer/devcontainer.json."
  prompt_value DEVCONTAINER_POSTCREATE_INSTALL "Allow online post-create dependency install?" "${DEVCONTAINER_POSTCREATE_INSTALL:-0}" "0 keeps offline fail-fast behavior; 1 explicitly allows make predev online."

  prompt_value CUDA_GO_TAGS "Go build tags for CUDA" "${CUDA_GO_TAGS:-$detected_cuda}" "Use cuda only when /opt/cuda has nvcc and runtime libs; '-' unsets."
  prompt_value OS_SMOKE_PRIVILEGE_CMD "Privilege command for os-enforcement smoke start" "${OS_SMOKE_PRIVILEGE_CMD:-}" "Example: sudo -E. Leave unset for normal root/passwordless-sudo detection."

  write_files
  print_next_steps
}

print_next_steps() {
  cat <<'NEXT'

Next steps:
  make dev-env-doctor
  make predev
  make dev

For a shell that should inherit the same values:
  set -a; . ./.env.dev; set +a
NEXT
}

print_exports() {
  load_existing
  for key in "${CONFIG_KEYS[@]}"; do
    local value
    value="$(get_var "$key")"
    [ -n "$value" ] || continue
    printf 'export %s=%s\n' "$key" "$(shell_quote "$value")"
  done
}

doctor() {
  load_existing
  echo "Dev env files:"
  [ -f "$SHELL_ENV_FILE" ] && echo "  shell: ${SHELL_ENV_FILE#$ROOT/}" || echo "  shell: missing (.env.dev)"
  [ -f "$MAKE_ENV_FILE" ] && echo "  make : ${MAKE_ENV_FILE#$ROOT/}" || echo "  make : missing (.env.dev.mk)"
  echo
  echo "Configured values:"
  for key in "${CONFIG_KEYS[@]}"; do
    local value
    value="$(get_var "$key")"
    [ -n "$value" ] || continue
    printf '  %-32s %s\n' "$key" "$value"
  done
  echo
  echo "Tool checks:"
  local missing=0
  for cmd in go make bun uv protoc zellij sudo; do
    if command -v "$cmd" >/dev/null 2>&1; then
      printf '  %-10s %s\n' "$cmd" "$(command -v "$cmd")"
    else
      printf '  %-10s MISSING\n' "$cmd"
      missing=1
    fi
  done
  local container_cli
  container_cli="${CONTAINER_CLI:-$(detect_container_cli)}"
  if [ -n "$container_cli" ] && command -v "$container_cli" >/dev/null 2>&1; then
    printf '  %-10s %s\n' "container" "$container_cli ($(command -v "$container_cli"))"
  else
    printf '  %-10s MISSING docker/podman\n' "container"
  fi
  echo
  echo "Effective devcontainer image from Makefile:"
  (cd "$ROOT" && make --no-print-directory dev-image) || missing=1
  return "$missing"
}

reset_config() {
  rm -f "$SHELL_ENV_FILE" "$MAKE_ENV_FILE"
  echo "Removed .env.dev and .env.dev.mk"
}

write_defaults() {
  load_existing
  apply_recommended_defaults
  write_files
  print_next_steps
}

cmd="${1:-configure}"
case "$cmd" in
  configure|config|wizard) configure ;;
  print|export|exports) print_exports ;;
  doctor|check) doctor ;;
  reset|clean) reset_config ;;
  defaults|default) write_defaults ;;
  help|-h|--help) usage ;;
  *) usage >&2; exit 64 ;;
esac
