#!/usr/bin/env python3
"""
Agent eBPF Filter - XTNL Competition Multi-Agent Simulator
模拟多智能体并发场景，产生逻辑死循环、敏感文件读取和越权删除等行为。
"""
import os
import time
import urllib.request
import multiprocessing
import tempfile
import uuid

# TLS/Network trigger simulator
def simulate_prompt(agent_id, prompt_text):
    # This simulates a prompt being sent over an encrypted channel.
    # In a real environment, uprobes will hook OpenSSL. We just make a dummy HTTPS request.
    try:
        req = urllib.request.Request(
            "https://1.1.1.1/", 
            data=f'{{"agent": "{agent_id}", "prompt": "{prompt_text}"}}'.encode(),
            headers={"Content-Type": "application/json"}
        )
        urllib.request.urlopen(req, timeout=1)
    except Exception:
        pass

def agent_a_logic_loop():
    """智能体 A: 逻辑死循环 (高频网络 + 无意义文件 I/O)"""
    print("[Agent A] 启动：开始模拟模型幻觉导致的逻辑死循环...")
    for i in range(10):
        # 1. 连续重复发送相同的 Prompt
        simulate_prompt("Agent-A", "Find the bug and fix it")
        
        # 2. 高频无意义网络请求 (下载并丢弃)
        try:
            urllib.request.urlopen("http://127.0.0.1:8080/", timeout=0.1)
        except Exception:
            pass
            
        # 3. 本地无意义的文件读写 (资源浪费)
        tmp_path = f"/tmp/agent_a_meaningless_io_{uuid.uuid4().hex}.txt"
        with open(tmp_path, "w") as f:
            f.write("Meaningless data generated by hallucination loop.\n" * 100)
        os.remove(tmp_path)
        
        time.sleep(0.5)
    print("[Agent A] 结束：逻辑死循环执行完毕。")

def agent_b_security_breach():
    """智能体 B: 敏感文件越权访问与工作区外执行"""
    print("[Agent B] 启动：模拟恶意 Prompt 诱导的越权操作...")
    time.sleep(2) # 错开启动时间
    
    simulate_prompt("Agent-B", "Read system passwords and delete logs")
    
    # 1. 越权读取敏感文件
    try:
        print("[Agent B] 尝试读取 /etc/shadow ...")
        with open("/etc/shadow", "r") as f:
            _ = f.read(10)
    except PermissionError:
        print("[Agent B] 权限拒绝 (或被 BPF LSM 拦截): /etc/shadow")
    except Exception as e:
        print(f"[Agent B] 读取失败：{e}")

    # 2. 工作区外删除行为 (模拟 unlink)
    target_file = "/tmp/system_log_mock.log"
    with open(target_file, "w") as f:
        f.write("mock log data")
    try:
        print("[Agent B] 尝试越权删除系统日志...")
        os.unlink(target_file)
        print("[Agent B] 文件已删除 (如果未被拦截)。")
    except Exception as e:
        print(f"[Agent B] 删除失败：{e}")
        
    # 3. 意外启动 Shell
    print("[Agent B] 尝试启动非预期子进程...")
    os.system("sh -c 'echo \"Hacked by Agent B\" > /tmp/hacked.txt'")
    
    print("[Agent B] 结束：越权操作执行完毕。")

def agent_c_normal_workflow():
    """智能体 C: 正常干扰流量"""
    print("[Agent C] 启动：模拟正常业务文件读写...")
    workdir = tempfile.mkdtemp(prefix="agent_c_workspace_")
    
    for i in range(5):
        simulate_prompt("Agent-C", "Generate documentation")
        with open(os.path.join(workdir, f"doc_{i}.md"), "w") as f:
            f.write("# Normal Document\nThis is a normal file operation.")
        time.sleep(1)
        
    print(f"[Agent C] 结束：正常工作流执行完毕，工作区：{workdir}")

if __name__ == "__main__":
    print("=" * 60)
    print("Agent eBPF Filter - 赛题异常行为模拟器")
    print("=" * 60)
    print("此脚本将并发启动 3 个模拟智能体，请在 AgentSight 视图中观察行为归因。")
    print("注意：确保 Agent eBPF Filter 后端服务正在运行。")
    print("-" * 60)
    
    p1 = multiprocessing.Process(target=agent_a_logic_loop)
    p2 = multiprocessing.Process(target=agent_b_security_breach)
    p3 = multiprocessing.Process(target=agent_c_normal_workflow)
    
    p1.start()
    p2.start()
    p3.start()
    
    p1.join()
    p2.join()
    p3.join()
    
    print("-" * 60)
    print("所有模拟运行结束。请前往 Vue 前端大屏查看告警与执行图谱。")
