// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AgentTlsCaptureRetprobeCtx struct {
	_         structs.HostLayout
	Buf       uint64
	LenPtr    uint64
	Len       uint32
	LibType   uint8
	Direction uint8
	Function  uint8
	_         [1]byte
}

type AgentTlsCaptureTlsFragment struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Tgid        uint32
	DataLen     uint32
	TotalLen    uint32
	OriginalLen uint32
	FragIndex   uint16
	FragCount   uint16
	LibType     uint8
	Direction   uint8
	Flags       uint8
	Function    uint8
	Comm        [16]int8
	Data        [960]int8
	_           [4]byte
}

// LoadAgentTlsCapture returns the embedded CollectionSpec for AgentTlsCapture.
func LoadAgentTlsCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentTlsCaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentTlsCapture: %w", err)
	}

	return spec, err
}

// LoadAgentTlsCaptureObjects loads AgentTlsCapture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentTlsCaptureObjects
//	*AgentTlsCapturePrograms
//	*AgentTlsCaptureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentTlsCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentTlsCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentTlsCaptureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureSpecs struct {
	AgentTlsCaptureProgramSpecs
	AgentTlsCaptureMapSpecs
	AgentTlsCaptureVariableSpecs
}

// AgentTlsCaptureProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureProgramSpecs struct {
	UprobeCryptoTlsConnRead     *ebpf.ProgramSpec `ebpf:"uprobe_crypto_tls_conn_read"`
	UprobeCryptoTlsConnWrite    *ebpf.ProgramSpec `ebpf:"uprobe_crypto_tls_conn_write"`
	UprobeGnutlsRecordRecv      *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_record_recv"`
	UprobeGnutlsRecordSend      *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_record_send"`
	UprobePrRead                *ebpf.ProgramSpec `ebpf:"uprobe_pr_read"`
	UprobePrWrite               *ebpf.ProgramSpec `ebpf:"uprobe_pr_write"`
	UprobeRustlsEncryptOutgoing *ebpf.ProgramSpec `ebpf:"uprobe_rustls_encrypt_outgoing"`
	UprobeSslRead               *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx             *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite              *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx            *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UprobeSslWriteEx2           *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex2"`
	UretprobeCryptoTlsConnRead  *ebpf.ProgramSpec `ebpf:"uretprobe_crypto_tls_conn_read"`
	UretprobeGnutlsRecordRecv   *ebpf.ProgramSpec `ebpf:"uretprobe_gnutls_record_recv"`
	UretprobePrRead             *ebpf.ProgramSpec `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead            *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx          *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx         *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
	UretprobeSslWriteEx2        *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex2"`
}

// AgentTlsCaptureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureMapSpecs struct {
	RetprobeBuf  *ebpf.MapSpec `ebpf:"retprobe_buf"`
	TlsEvents    *ebpf.MapSpec `ebpf:"tls_events"`
	TlsProbeHits *ebpf.MapSpec `ebpf:"tls_probe_hits"`
	TlsScratch   *ebpf.MapSpec `ebpf:"tls_scratch"`
}

// AgentTlsCaptureVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureVariableSpecs struct {
	TlsFragmentTypeAnchor *ebpf.VariableSpec `ebpf:"tls_fragment_type_anchor"`
}

// AgentTlsCaptureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureObjects struct {
	AgentTlsCapturePrograms
	AgentTlsCaptureMaps
	AgentTlsCaptureVariables
}

func (o *AgentTlsCaptureObjects) Close() error {
	return _AgentTlsCaptureClose(
		&o.AgentTlsCapturePrograms,
		&o.AgentTlsCaptureMaps,
	)
}

// AgentTlsCaptureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureMaps struct {
	RetprobeBuf  *ebpf.Map `ebpf:"retprobe_buf"`
	TlsEvents    *ebpf.Map `ebpf:"tls_events"`
	TlsProbeHits *ebpf.Map `ebpf:"tls_probe_hits"`
	TlsScratch   *ebpf.Map `ebpf:"tls_scratch"`
}

func (m *AgentTlsCaptureMaps) Close() error {
	return _AgentTlsCaptureClose(
		m.RetprobeBuf,
		m.TlsEvents,
		m.TlsProbeHits,
		m.TlsScratch,
	)
}

// AgentTlsCaptureVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureVariables struct {
	TlsFragmentTypeAnchor *ebpf.Variable `ebpf:"tls_fragment_type_anchor"`
}

// AgentTlsCapturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCapturePrograms struct {
	UprobeCryptoTlsConnRead     *ebpf.Program `ebpf:"uprobe_crypto_tls_conn_read"`
	UprobeCryptoTlsConnWrite    *ebpf.Program `ebpf:"uprobe_crypto_tls_conn_write"`
	UprobeGnutlsRecordRecv      *ebpf.Program `ebpf:"uprobe_gnutls_record_recv"`
	UprobeGnutlsRecordSend      *ebpf.Program `ebpf:"uprobe_gnutls_record_send"`
	UprobePrRead                *ebpf.Program `ebpf:"uprobe_pr_read"`
	UprobePrWrite               *ebpf.Program `ebpf:"uprobe_pr_write"`
	UprobeRustlsEncryptOutgoing *ebpf.Program `ebpf:"uprobe_rustls_encrypt_outgoing"`
	UprobeSslRead               *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx             *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite              *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx            *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UprobeSslWriteEx2           *ebpf.Program `ebpf:"uprobe_ssl_write_ex2"`
	UretprobeCryptoTlsConnRead  *ebpf.Program `ebpf:"uretprobe_crypto_tls_conn_read"`
	UretprobeGnutlsRecordRecv   *ebpf.Program `ebpf:"uretprobe_gnutls_record_recv"`
	UretprobePrRead             *ebpf.Program `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead            *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx          *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx         *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
	UretprobeSslWriteEx2        *ebpf.Program `ebpf:"uretprobe_ssl_write_ex2"`
}

func (p *AgentTlsCapturePrograms) Close() error {
	return _AgentTlsCaptureClose(
		p.UprobeCryptoTlsConnRead,
		p.UprobeCryptoTlsConnWrite,
		p.UprobeGnutlsRecordRecv,
		p.UprobeGnutlsRecordSend,
		p.UprobePrRead,
		p.UprobePrWrite,
		p.UprobeRustlsEncryptOutgoing,
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UprobeSslWriteEx2,
		p.UretprobeCryptoTlsConnRead,
		p.UretprobeGnutlsRecordRecv,
		p.UretprobePrRead,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslWriteEx,
		p.UretprobeSslWriteEx2,
	)
}

func _AgentTlsCaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agenttlscapture_x86_bpfel.o
var _AgentTlsCaptureBytes []byte
