// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadAgentTracker returns the embedded CollectionSpec for AgentTracker.
func LoadAgentTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentTracker: %w", err)
	}

	return spec, err
}

// LoadAgentTrackerObjects loads AgentTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentTrackerObjects
//	*AgentTrackerPrograms
//	*AgentTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTrackerSpecs struct {
	AgentTrackerProgramSpecs
	AgentTrackerMapSpecs
	AgentTrackerVariableSpecs
}

// AgentTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTrackerProgramSpecs struct {
	TracepointSyscallsSysEnterBind     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterIoctl    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
	TracepointSyscallsSysEnterMkdirat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mkdirat"`
	TracepointSyscallsSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_recvfrom"`
	TracepointSyscallsSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysEnterUnlinkat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
}

// AgentTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTrackerMapSpecs struct {
	AgentPids    *ebpf.MapSpec `ebpf:"agent_pids"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	TrackedComms *ebpf.MapSpec `ebpf:"tracked_comms"`
	TrackedPaths *ebpf.MapSpec `ebpf:"tracked_paths"`
}

// AgentTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTrackerVariableSpecs struct {
}

// AgentTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTrackerObjects struct {
	AgentTrackerPrograms
	AgentTrackerMaps
	AgentTrackerVariables
}

func (o *AgentTrackerObjects) Close() error {
	return _AgentTrackerClose(
		&o.AgentTrackerPrograms,
		&o.AgentTrackerMaps,
	)
}

// AgentTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTrackerMaps struct {
	AgentPids    *ebpf.Map `ebpf:"agent_pids"`
	Events       *ebpf.Map `ebpf:"events"`
	TrackedComms *ebpf.Map `ebpf:"tracked_comms"`
	TrackedPaths *ebpf.Map `ebpf:"tracked_paths"`
}

func (m *AgentTrackerMaps) Close() error {
	return _AgentTrackerClose(
		m.AgentPids,
		m.Events,
		m.TrackedComms,
		m.TrackedPaths,
	)
}

// AgentTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTrackerVariables struct {
}

// AgentTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTrackerPrograms struct {
	TracepointSyscallsSysEnterBind     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterConnect  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterIoctl    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
	TracepointSyscallsSysEnterMkdirat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mkdirat"`
	TracepointSyscallsSysEnterOpenat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterRecvfrom *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_recvfrom"`
	TracepointSyscallsSysEnterSendto   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysEnterUnlinkat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
}

func (p *AgentTrackerPrograms) Close() error {
	return _AgentTrackerClose(
		p.TracepointSyscallsSysEnterBind,
		p.TracepointSyscallsSysEnterConnect,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterIoctl,
		p.TracepointSyscallsSysEnterMkdirat,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterRecvfrom,
		p.TracepointSyscallsSysEnterSendto,
		p.TracepointSyscallsSysEnterUnlinkat,
	)
}

func _AgentTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agenttracker_bpfel.o
var _AgentTrackerBytes []byte
