// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AgentLsmEnforcerLsmEnforcerStats struct {
	_           structs.HostLayout
	ExecChecked uint64
	ExecBlocked uint64
	FileChecked uint64
	FileBlocked uint64
}

type AgentLsmEnforcerLsmNameKey struct {
	_    structs.HostLayout
	Name [64]int8
}

type AgentLsmEnforcerLsmPathKey struct {
	_    structs.HostLayout
	Path [256]int8
}

// LoadAgentLsmEnforcer returns the embedded CollectionSpec for AgentLsmEnforcer.
func LoadAgentLsmEnforcer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentLsmEnforcerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentLsmEnforcer: %w", err)
	}

	return spec, err
}

// LoadAgentLsmEnforcerObjects loads AgentLsmEnforcer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentLsmEnforcerObjects
//	*AgentLsmEnforcerPrograms
//	*AgentLsmEnforcerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentLsmEnforcerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentLsmEnforcer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentLsmEnforcerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentLsmEnforcerSpecs struct {
	AgentLsmEnforcerProgramSpecs
	AgentLsmEnforcerMapSpecs
	AgentLsmEnforcerVariableSpecs
}

// AgentLsmEnforcerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentLsmEnforcerProgramSpecs struct {
	LsmEnforceBprmCheck      *ebpf.ProgramSpec `ebpf:"lsm_enforce_bprm_check"`
	LsmEnforceFileMprotect   *ebpf.ProgramSpec `ebpf:"lsm_enforce_file_mprotect"`
	LsmEnforceFileOpen       *ebpf.ProgramSpec `ebpf:"lsm_enforce_file_open"`
	LsmEnforceFilePermission *ebpf.ProgramSpec `ebpf:"lsm_enforce_file_permission"`
	LsmEnforceInodeCreate    *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_create"`
	LsmEnforceInodeLink      *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_link"`
	LsmEnforceInodeMkdir     *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_mkdir"`
	LsmEnforceInodeMknod     *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_mknod"`
	LsmEnforceInodeRename    *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_rename"`
	LsmEnforceInodeRmdir     *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_rmdir"`
	LsmEnforceInodeSetattr   *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_setattr"`
	LsmEnforceInodeSymlink   *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_symlink"`
	LsmEnforceInodeUnlink    *ebpf.ProgramSpec `ebpf:"lsm_enforce_inode_unlink"`
	LsmEnforceMmapFile       *ebpf.ProgramSpec `ebpf:"lsm_enforce_mmap_file"`
}

// AgentLsmEnforcerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentLsmEnforcerMapSpecs struct {
	LsmBlockedExecNames *ebpf.MapSpec `ebpf:"lsm_blocked_exec_names"`
	LsmBlockedExecPaths *ebpf.MapSpec `ebpf:"lsm_blocked_exec_paths"`
	LsmBlockedFileNames *ebpf.MapSpec `ebpf:"lsm_blocked_file_names"`
	LsmEnforcerStatsMap *ebpf.MapSpec `ebpf:"lsm_enforcer_stats_map"`
}

// AgentLsmEnforcerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentLsmEnforcerVariableSpecs struct {
	LsmEnforcerStatsTypeAnchor *ebpf.VariableSpec `ebpf:"lsm_enforcer_stats_type_anchor"`
}

// AgentLsmEnforcerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentLsmEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentLsmEnforcerObjects struct {
	AgentLsmEnforcerPrograms
	AgentLsmEnforcerMaps
	AgentLsmEnforcerVariables
}

func (o *AgentLsmEnforcerObjects) Close() error {
	return _AgentLsmEnforcerClose(
		&o.AgentLsmEnforcerPrograms,
		&o.AgentLsmEnforcerMaps,
	)
}

// AgentLsmEnforcerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentLsmEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentLsmEnforcerMaps struct {
	LsmBlockedExecNames *ebpf.Map `ebpf:"lsm_blocked_exec_names"`
	LsmBlockedExecPaths *ebpf.Map `ebpf:"lsm_blocked_exec_paths"`
	LsmBlockedFileNames *ebpf.Map `ebpf:"lsm_blocked_file_names"`
	LsmEnforcerStatsMap *ebpf.Map `ebpf:"lsm_enforcer_stats_map"`
}

func (m *AgentLsmEnforcerMaps) Close() error {
	return _AgentLsmEnforcerClose(
		m.LsmBlockedExecNames,
		m.LsmBlockedExecPaths,
		m.LsmBlockedFileNames,
		m.LsmEnforcerStatsMap,
	)
}

// AgentLsmEnforcerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentLsmEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentLsmEnforcerVariables struct {
	LsmEnforcerStatsTypeAnchor *ebpf.Variable `ebpf:"lsm_enforcer_stats_type_anchor"`
}

// AgentLsmEnforcerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentLsmEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentLsmEnforcerPrograms struct {
	LsmEnforceBprmCheck      *ebpf.Program `ebpf:"lsm_enforce_bprm_check"`
	LsmEnforceFileMprotect   *ebpf.Program `ebpf:"lsm_enforce_file_mprotect"`
	LsmEnforceFileOpen       *ebpf.Program `ebpf:"lsm_enforce_file_open"`
	LsmEnforceFilePermission *ebpf.Program `ebpf:"lsm_enforce_file_permission"`
	LsmEnforceInodeCreate    *ebpf.Program `ebpf:"lsm_enforce_inode_create"`
	LsmEnforceInodeLink      *ebpf.Program `ebpf:"lsm_enforce_inode_link"`
	LsmEnforceInodeMkdir     *ebpf.Program `ebpf:"lsm_enforce_inode_mkdir"`
	LsmEnforceInodeMknod     *ebpf.Program `ebpf:"lsm_enforce_inode_mknod"`
	LsmEnforceInodeRename    *ebpf.Program `ebpf:"lsm_enforce_inode_rename"`
	LsmEnforceInodeRmdir     *ebpf.Program `ebpf:"lsm_enforce_inode_rmdir"`
	LsmEnforceInodeSetattr   *ebpf.Program `ebpf:"lsm_enforce_inode_setattr"`
	LsmEnforceInodeSymlink   *ebpf.Program `ebpf:"lsm_enforce_inode_symlink"`
	LsmEnforceInodeUnlink    *ebpf.Program `ebpf:"lsm_enforce_inode_unlink"`
	LsmEnforceMmapFile       *ebpf.Program `ebpf:"lsm_enforce_mmap_file"`
}

func (p *AgentLsmEnforcerPrograms) Close() error {
	return _AgentLsmEnforcerClose(
		p.LsmEnforceBprmCheck,
		p.LsmEnforceFileMprotect,
		p.LsmEnforceFileOpen,
		p.LsmEnforceFilePermission,
		p.LsmEnforceInodeCreate,
		p.LsmEnforceInodeLink,
		p.LsmEnforceInodeMkdir,
		p.LsmEnforceInodeMknod,
		p.LsmEnforceInodeRename,
		p.LsmEnforceInodeRmdir,
		p.LsmEnforceInodeSetattr,
		p.LsmEnforceInodeSymlink,
		p.LsmEnforceInodeUnlink,
		p.LsmEnforceMmapFile,
	)
}

func _AgentLsmEnforcerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agentlsmenforcer_bpfel.o
var _AgentLsmEnforcerBytes []byte
