// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AgentCgroupSandboxCgroupSandboxStats struct {
	_              structs.HostLayout
	ConnectChecked uint64
	ConnectBlocked uint64
	ConnectAllowed uint64
}

type AgentCgroupSandboxIp6BlockKey struct {
	_    structs.HostLayout
	Addr [4]uint32
}

// LoadAgentCgroupSandbox returns the embedded CollectionSpec for AgentCgroupSandbox.
func LoadAgentCgroupSandbox() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentCgroupSandboxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentCgroupSandbox: %w", err)
	}

	return spec, err
}

// LoadAgentCgroupSandboxObjects loads AgentCgroupSandbox and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentCgroupSandboxObjects
//	*AgentCgroupSandboxPrograms
//	*AgentCgroupSandboxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentCgroupSandboxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentCgroupSandbox()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentCgroupSandboxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentCgroupSandboxSpecs struct {
	AgentCgroupSandboxProgramSpecs
	AgentCgroupSandboxMapSpecs
	AgentCgroupSandboxVariableSpecs
}

// AgentCgroupSandboxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentCgroupSandboxProgramSpecs struct {
	CgroupSandboxConnect4 *ebpf.ProgramSpec `ebpf:"cgroup_sandbox_connect4"`
	CgroupSandboxConnect6 *ebpf.ProgramSpec `ebpf:"cgroup_sandbox_connect6"`
	CgroupSandboxSendmsg4 *ebpf.ProgramSpec `ebpf:"cgroup_sandbox_sendmsg4"`
	CgroupSandboxSendmsg6 *ebpf.ProgramSpec `ebpf:"cgroup_sandbox_sendmsg6"`
}

// AgentCgroupSandboxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentCgroupSandboxMapSpecs struct {
	CgroupBlocklist    *ebpf.MapSpec `ebpf:"cgroup_blocklist"`
	CgroupSandboxStats *ebpf.MapSpec `ebpf:"cgroup_sandbox_stats"`
	Ip6Blocklist       *ebpf.MapSpec `ebpf:"ip6_blocklist"`
	IpBlocklist        *ebpf.MapSpec `ebpf:"ip_blocklist"`
	PortBlocklist      *ebpf.MapSpec `ebpf:"port_blocklist"`
}

// AgentCgroupSandboxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentCgroupSandboxVariableSpecs struct {
}

// AgentCgroupSandboxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentCgroupSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentCgroupSandboxObjects struct {
	AgentCgroupSandboxPrograms
	AgentCgroupSandboxMaps
	AgentCgroupSandboxVariables
}

func (o *AgentCgroupSandboxObjects) Close() error {
	return _AgentCgroupSandboxClose(
		&o.AgentCgroupSandboxPrograms,
		&o.AgentCgroupSandboxMaps,
	)
}

// AgentCgroupSandboxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentCgroupSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentCgroupSandboxMaps struct {
	CgroupBlocklist    *ebpf.Map `ebpf:"cgroup_blocklist"`
	CgroupSandboxStats *ebpf.Map `ebpf:"cgroup_sandbox_stats"`
	Ip6Blocklist       *ebpf.Map `ebpf:"ip6_blocklist"`
	IpBlocklist        *ebpf.Map `ebpf:"ip_blocklist"`
	PortBlocklist      *ebpf.Map `ebpf:"port_blocklist"`
}

func (m *AgentCgroupSandboxMaps) Close() error {
	return _AgentCgroupSandboxClose(
		m.CgroupBlocklist,
		m.CgroupSandboxStats,
		m.Ip6Blocklist,
		m.IpBlocklist,
		m.PortBlocklist,
	)
}

// AgentCgroupSandboxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentCgroupSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentCgroupSandboxVariables struct {
}

// AgentCgroupSandboxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentCgroupSandboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentCgroupSandboxPrograms struct {
	CgroupSandboxConnect4 *ebpf.Program `ebpf:"cgroup_sandbox_connect4"`
	CgroupSandboxConnect6 *ebpf.Program `ebpf:"cgroup_sandbox_connect6"`
	CgroupSandboxSendmsg4 *ebpf.Program `ebpf:"cgroup_sandbox_sendmsg4"`
	CgroupSandboxSendmsg6 *ebpf.Program `ebpf:"cgroup_sandbox_sendmsg6"`
}

func (p *AgentCgroupSandboxPrograms) Close() error {
	return _AgentCgroupSandboxClose(
		p.CgroupSandboxConnect4,
		p.CgroupSandboxConnect6,
		p.CgroupSandboxSendmsg4,
		p.CgroupSandboxSendmsg6,
	)
}

func _AgentCgroupSandboxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agentcgroupsandbox_bpfel.o
var _AgentCgroupSandboxBytes []byte
