// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AgentTlsCaptureRetprobeCtx struct {
	_   structs.HostLayout
	Buf uint64
}

type AgentTlsCaptureTlsFragment struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Tgid        uint32
	DataLen     uint32
	TotalLen    uint32
	FragIndex   uint16
	FragCount   uint16
	LibType     uint8
	Direction   uint8
	Comm        [16]int8
	Data        [960]int8
	_           [2]byte
}

// LoadAgentTlsCapture returns the embedded CollectionSpec for AgentTlsCapture.
func LoadAgentTlsCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentTlsCaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentTlsCapture: %w", err)
	}

	return spec, err
}

// LoadAgentTlsCaptureObjects loads AgentTlsCapture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentTlsCaptureObjects
//	*AgentTlsCapturePrograms
//	*AgentTlsCaptureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentTlsCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentTlsCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentTlsCaptureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureSpecs struct {
	AgentTlsCaptureProgramSpecs
	AgentTlsCaptureMapSpecs
	AgentTlsCaptureVariableSpecs
}

// AgentTlsCaptureProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureProgramSpecs struct {
	UprobeCryptoTlsConnRead    *ebpf.ProgramSpec `ebpf:"uprobe_crypto_tls_conn_read"`
	UprobeCryptoTlsConnWrite   *ebpf.ProgramSpec `ebpf:"uprobe_crypto_tls_conn_write"`
	UprobeGnutlsRecordRecv     *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_record_recv"`
	UprobeGnutlsRecordSend     *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_record_send"`
	UprobePrRead               *ebpf.ProgramSpec `ebpf:"uprobe_pr_read"`
	UprobePrWrite              *ebpf.ProgramSpec `ebpf:"uprobe_pr_write"`
	UprobeSslRead              *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite             *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeCryptoTlsConnRead *ebpf.ProgramSpec `ebpf:"uretprobe_crypto_tls_conn_read"`
	UretprobeGnutlsRecordRecv  *ebpf.ProgramSpec `ebpf:"uretprobe_gnutls_record_recv"`
	UretprobePrRead            *ebpf.ProgramSpec `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead           *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
}

// AgentTlsCaptureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureMapSpecs struct {
	RetprobeBuf *ebpf.MapSpec `ebpf:"retprobe_buf"`
	TlsEvents   *ebpf.MapSpec `ebpf:"tls_events"`
}

// AgentTlsCaptureVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentTlsCaptureVariableSpecs struct {
	TlsFragmentTypeAnchor *ebpf.VariableSpec `ebpf:"tls_fragment_type_anchor"`
}

// AgentTlsCaptureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureObjects struct {
	AgentTlsCapturePrograms
	AgentTlsCaptureMaps
	AgentTlsCaptureVariables
}

func (o *AgentTlsCaptureObjects) Close() error {
	return _AgentTlsCaptureClose(
		&o.AgentTlsCapturePrograms,
		&o.AgentTlsCaptureMaps,
	)
}

// AgentTlsCaptureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureMaps struct {
	RetprobeBuf *ebpf.Map `ebpf:"retprobe_buf"`
	TlsEvents   *ebpf.Map `ebpf:"tls_events"`
}

func (m *AgentTlsCaptureMaps) Close() error {
	return _AgentTlsCaptureClose(
		m.RetprobeBuf,
		m.TlsEvents,
	)
}

// AgentTlsCaptureVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCaptureVariables struct {
	TlsFragmentTypeAnchor *ebpf.Variable `ebpf:"tls_fragment_type_anchor"`
}

// AgentTlsCapturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentTlsCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentTlsCapturePrograms struct {
	UprobeCryptoTlsConnRead    *ebpf.Program `ebpf:"uprobe_crypto_tls_conn_read"`
	UprobeCryptoTlsConnWrite   *ebpf.Program `ebpf:"uprobe_crypto_tls_conn_write"`
	UprobeGnutlsRecordRecv     *ebpf.Program `ebpf:"uprobe_gnutls_record_recv"`
	UprobeGnutlsRecordSend     *ebpf.Program `ebpf:"uprobe_gnutls_record_send"`
	UprobePrRead               *ebpf.Program `ebpf:"uprobe_pr_read"`
	UprobePrWrite              *ebpf.Program `ebpf:"uprobe_pr_write"`
	UprobeSslRead              *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite             *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeCryptoTlsConnRead *ebpf.Program `ebpf:"uretprobe_crypto_tls_conn_read"`
	UretprobeGnutlsRecordRecv  *ebpf.Program `ebpf:"uretprobe_gnutls_record_recv"`
	UretprobePrRead            *ebpf.Program `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead           *ebpf.Program `ebpf:"uretprobe_ssl_read"`
}

func (p *AgentTlsCapturePrograms) Close() error {
	return _AgentTlsCaptureClose(
		p.UprobeCryptoTlsConnRead,
		p.UprobeCryptoTlsConnWrite,
		p.UprobeGnutlsRecordRecv,
		p.UprobeGnutlsRecordSend,
		p.UprobePrRead,
		p.UprobePrWrite,
		p.UprobeSslRead,
		p.UprobeSslWrite,
		p.UretprobeCryptoTlsConnRead,
		p.UretprobeGnutlsRecordRecv,
		p.UretprobePrRead,
		p.UretprobeSslRead,
	)
}

func _AgentTlsCaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agenttlscapture_x86_bpfel.o
var _AgentTlsCaptureBytes []byte
