// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CodexSyscallTrackerCodexSyscallEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	DataLen     uint32
	Direction   uint8
	Comm        [16]int8
	Data        [960]int8
	_           [7]byte
}

// LoadCodexSyscallTracker returns the embedded CollectionSpec for CodexSyscallTracker.
func LoadCodexSyscallTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CodexSyscallTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CodexSyscallTracker: %w", err)
	}

	return spec, err
}

// LoadCodexSyscallTrackerObjects loads CodexSyscallTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CodexSyscallTrackerObjects
//	*CodexSyscallTrackerPrograms
//	*CodexSyscallTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCodexSyscallTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCodexSyscallTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CodexSyscallTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CodexSyscallTrackerSpecs struct {
	CodexSyscallTrackerProgramSpecs
	CodexSyscallTrackerMapSpecs
	CodexSyscallTrackerVariableSpecs
}

// CodexSyscallTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CodexSyscallTrackerProgramSpecs struct {
	TraceCodexRead  *ebpf.ProgramSpec `ebpf:"trace_codex_read"`
	TraceCodexWrite *ebpf.ProgramSpec `ebpf:"trace_codex_write"`
}

// CodexSyscallTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CodexSyscallTrackerMapSpecs struct {
	CodexEvents *ebpf.MapSpec `ebpf:"codex_events"`
}

// CodexSyscallTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CodexSyscallTrackerVariableSpecs struct {
	CodexEventAnchor *ebpf.VariableSpec `ebpf:"codex_event_anchor"`
}

// CodexSyscallTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCodexSyscallTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CodexSyscallTrackerObjects struct {
	CodexSyscallTrackerPrograms
	CodexSyscallTrackerMaps
	CodexSyscallTrackerVariables
}

func (o *CodexSyscallTrackerObjects) Close() error {
	return _CodexSyscallTrackerClose(
		&o.CodexSyscallTrackerPrograms,
		&o.CodexSyscallTrackerMaps,
	)
}

// CodexSyscallTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCodexSyscallTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CodexSyscallTrackerMaps struct {
	CodexEvents *ebpf.Map `ebpf:"codex_events"`
}

func (m *CodexSyscallTrackerMaps) Close() error {
	return _CodexSyscallTrackerClose(
		m.CodexEvents,
	)
}

// CodexSyscallTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCodexSyscallTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CodexSyscallTrackerVariables struct {
	CodexEventAnchor *ebpf.Variable `ebpf:"codex_event_anchor"`
}

// CodexSyscallTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCodexSyscallTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CodexSyscallTrackerPrograms struct {
	TraceCodexRead  *ebpf.Program `ebpf:"trace_codex_read"`
	TraceCodexWrite *ebpf.Program `ebpf:"trace_codex_write"`
}

func (p *CodexSyscallTrackerPrograms) Close() error {
	return _CodexSyscallTrackerClose(
		p.TraceCodexRead,
		p.TraceCodexWrite,
	)
}

func _CodexSyscallTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed codexsyscalltracker_x86_bpfel.o
var _CodexSyscallTrackerBytes []byte
