[build]
target = "index.html"
dist = "dist"
filehash = false

[watch]
watch = ["src", "index.html"]

[serve]
addresses = ["127.0.0.1"]
port = 5173
open = false
headers = { "Cross-Origin-Embedder-Policy" = "require-corp", "Cross-Origin-Opener-Policy" = "same-origin" }
