import type { VisualRecipe } from "./types";

export const visualRecipes: VisualRecipe[] = [
  {
    id: "process-nc-block",
    name: "阻断 nc 执行",
    description: "最小闭环：bprm_check_security + comm/name 条件 + BLOCK。",
    tags: ["process", "LSM", "BLOCK"],
    version: 1,
    trigger: "process",
    action: "BLOCK",
    mapMode: "NONE",
    mapKey: "pid",
    mapLimit: 10,
    conditions: {
      id: "root",
      type: "AND",
      children: [
        {
          id: "recipe-nc-comm",
          type: "CONDITION",
          field: "comm",
          operator: "==",
          value: "nc",
        },
      ],
    },
  },
  {
    id: "reverse-shell-ports",
    name: "反连端口强杀",
    description:
      "socket_connect 上组合 comm + 多端口 OR，并用 COUNTER 限频兜底。",
    tags: ["socket", "OR", "KILL", "COUNTER"],
    version: 1,
    trigger: "socket_connect",
    action: "KILL",
    mapMode: "COUNTER",
    mapKey: "pid",
    mapLimit: 3,
    conditions: {
      id: "root",
      type: "AND",
      children: [
        {
          id: "recipe-rev-comm",
          type: "CONDITION",
          field: "comm",
          operator: "==",
          value: "nc",
        },
        {
          id: "recipe-rev-ports",
          type: "OR",
          children: [
            {
              id: "recipe-rev-port-4444",
              type: "CONDITION",
              field: "port",
              operator: "==",
              value: "4444",
            },
            {
              id: "recipe-rev-port-5555",
              type: "CONDITION",
              field: "port",
              operator: "==",
              value: "5555",
            },
          ],
        },
      ],
    },
  },
  {
    id: "ssh-key-read-protect",
    name: "SSH 私钥读取保护",
    description: "file_open 上拦截非 root 对 id_rsa / id_ed25519 的读取打开。",
    tags: ["file_open", "AND", "OR"],
    version: 1,
    trigger: "file_open",
    action: "BLOCK",
    mapMode: "NONE",
    mapKey: "pid",
    mapLimit: 10,
    conditions: {
      id: "root",
      type: "AND",
      children: [
        {
          id: "recipe-ssh-uid",
          type: "CONDITION",
          field: "uid",
          operator: "!=",
          value: "0",
        },
        {
          id: "recipe-ssh-files",
          type: "OR",
          children: [
            {
              id: "recipe-ssh-rsa",
              type: "CONDITION",
              field: "basename",
              operator: "==",
              value: "id_rsa",
            },
            {
              id: "recipe-ssh-ed25519",
              type: "CONDITION",
              field: "basename",
              operator: "==",
              value: "id_ed25519",
            },
          ],
        },
      ],
    },
  },
  {
    id: "ransomware-rename-watch",
    name: "勒索重命名审计",
    description:
      "inode_rename 上关注 shadow / .env / .key 等敏感名称，先告警审计。",
    tags: ["rename", "ALERT", "OR"],
    version: 1,
    trigger: "inode_rename",
    action: "ALERT",
    mapMode: "NONE",
    mapKey: "pid",
    mapLimit: 10,
    conditions: {
      id: "root",
      type: "OR",
      children: [
        {
          id: "recipe-ren-shadow",
          type: "CONDITION",
          field: "basename",
          operator: "==",
          value: "shadow",
        },
        {
          id: "recipe-ren-env",
          type: "CONDITION",
          field: "basename",
          operator: "ends_with",
          value: ".env",
        },
        {
          id: "recipe-ren-key",
          type: "CONDITION",
          field: "basename",
          operator: "ends_with",
          value: ".key",
        },
      ],
    },
  },
  {
    id: "mprotect-rwx-kill",
    name: "RWX 内存强杀",
    description: "file_mprotect 上对脚本/解释器进程启用 KILL 响应。",
    tags: ["mprotect", "KILL", "OR"],
    version: 1,
    trigger: "file_mprotect",
    action: "KILL",
    mapMode: "COUNTER",
    mapKey: "comm",
    mapLimit: 2,
    conditions: {
      id: "root",
      type: "OR",
      children: [
        {
          id: "recipe-mprot-python",
          type: "CONDITION",
          field: "comm",
          operator: "starts_with",
          value: "python",
        },
        {
          id: "recipe-mprot-node",
          type: "CONDITION",
          field: "comm",
          operator: "==",
          value: "node",
        },
        {
          id: "recipe-mprot-perl",
          type: "CONDITION",
          field: "comm",
          operator: "==",
          value: "perl",
        },
      ],
    },
  },
];
